-- ===========================================================================
-- 0001_partitions.sql — partitioning, RLS, and immutability (SPEC §6.13/§6.15/§6.16)
--
-- Drizzle does not emit `PARTITION BY`, so the generated 0000 migration creates the
-- eight RANGE(created_at) tables and the one LIST(grain) table as PLAIN tables. This
-- migration DROPs those (empty, freshly-created) tables and recreates them as
-- partitioned parents, then adds the partition-maintenance helper, initial partitions,
-- row-level security, and the immutability triggers.
--
-- B1 (SPEC §29.2): every partitioned PK/unique includes `created_at`, so
-- `CREATE TABLE … PARTITION BY` succeeds ("unique constraint must include all
-- partitioning columns" is satisfied).
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. Drop the plain versions generated by 0000 (empty on a fresh DB; no inbound FKs).
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS "observation_event";--> statement-breakpoint
DROP TABLE IF EXISTS "observation";--> statement-breakpoint
DROP TABLE IF EXISTS "trace_summary";--> statement-breakpoint
DROP TABLE IF EXISTS "policy_decision";--> statement-breakpoint
DROP TABLE IF EXISTS "usage_record";--> statement-breakpoint
DROP TABLE IF EXISTS "cost_ledger";--> statement-breakpoint
DROP TABLE IF EXISTS "audit_event";--> statement-breakpoint
DROP TABLE IF EXISTS "budget_reservation";--> statement-breakpoint
DROP TABLE IF EXISTS "usage_aggregate";--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 2. Recreate as partitioned parents. PARTITION BY RANGE(created_at) monthly (§6.13),
--    except usage_aggregate which is PARTITION BY LIST(grain).
-- ---------------------------------------------------------------------------
CREATE TABLE "budget_reservation" (
	"id" text NOT NULL,
	"workspace_id" text NOT NULL,
	"budget_account_id" text NOT NULL,
	"request_id" text NOT NULL,
	"estimated_input_tokens" bigint NOT NULL,
	"max_output_tokens" bigint NOT NULL,
	"reserved_microusd" bigint NOT NULL,
	"reserved_tokens" bigint,
	"status" text NOT NULL,
	"reconciled_microusd" bigint,
	"reconciled_tokens" bigint,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"reconciled_at" timestamp with time zone,
	CONSTRAINT "budget_reservation_id_created_at_pk" PRIMARY KEY("id","created_at"),
	CONSTRAINT "reservation_reserved_microusd_chk" CHECK ("reserved_microusd" >= 0),
	CONSTRAINT "reservation_status_chk" CHECK ("status" IN ('reserved','committed','rolled_back','expired'))
) PARTITION BY RANGE ("created_at");--> statement-breakpoint

CREATE TABLE "observation_event" (
	"id" text NOT NULL,
	"workspace_id" text NOT NULL,
	"trace_id" text NOT NULL,
	"span_id" text NOT NULL,
	"parent_span_id" text,
	"installation_id" text NOT NULL,
	"profile_mode" text NOT NULL,
	"app_id" text,
	"action_id" text,
	"route_id" text,
	"route_revision_id" text,
	"virtual_key_id" text,
	"kind" text NOT NULL,
	"seq" integer NOT NULL,
	"producer_id" text NOT NULL,
	"idempotency_key" text NOT NULL,
	"payload" jsonb NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "observation_event_id_created_at_pk" PRIMARY KEY("id","created_at"),
	CONSTRAINT "observation_event_kind_chk" CHECK ("kind" IN ('accepted','provider_attempt','terminal','annotation'))
) PARTITION BY RANGE ("created_at");--> statement-breakpoint

CREATE TABLE "observation" (
	"id" text NOT NULL,
	"workspace_id" text NOT NULL,
	"trace_id" text NOT NULL,
	"installation_id" text NOT NULL,
	"profile_mode" text NOT NULL,
	"route_id" text,
	"route_revision_id" text,
	"public_name" text,
	"endpoint_kind" text,
	"final_provider" text,
	"final_offering_id" text,
	"adapter_revision" text,
	"price_revision_id" text,
	"app_id" text,
	"action_id" text,
	"team_id" text,
	"cost_center_id" text,
	"virtual_key_id" text,
	"status" text NOT NULL,
	"http_status" integer,
	"input_tokens" bigint,
	"output_tokens" bigint,
	"cached_tokens" bigint,
	"reasoning_tokens" bigint,
	"cache_write_tokens" bigint,
	"audio_input_tokens" bigint,
	"audio_output_tokens" bigint,
	"cost_microusd" bigint,
	"cost_fidelity" text,
	"latency_ms" integer,
	"ttfb_ms" integer,
	"attempts" integer DEFAULT 1 NOT NULL,
	"failovers" integer DEFAULT 0 NOT NULL,
	"policy_decision_id" text,
	"reason_codes" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"capture_ref" jsonb,
	"compacted" boolean DEFAULT false NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "observation_id_created_at_pk" PRIMARY KEY("id","created_at"),
	CONSTRAINT "observation_status_chk" CHECK ("status" IN ('ok','error','denied','clamped','timeout')),
	CONSTRAINT "observation_cost_fidelity_chk" CHECK ("cost_fidelity" IN ('exact','estimated','unknown'))
) PARTITION BY RANGE ("created_at");--> statement-breakpoint

CREATE TABLE "trace_summary" (
	"workspace_id" text NOT NULL,
	"trace_id" text NOT NULL,
	"root_observation_id" text NOT NULL,
	"span_count" integer NOT NULL,
	"error" boolean NOT NULL,
	"total_cost_microusd" bigint,
	"total_latency_ms" integer,
	"started_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "trace_summary_workspace_id_trace_id_created_at_pk" PRIMARY KEY("workspace_id","trace_id","created_at")
) PARTITION BY RANGE ("created_at");--> statement-breakpoint

CREATE TABLE "policy_decision" (
	"id" text NOT NULL,
	"workspace_id" text NOT NULL,
	"request_id" text NOT NULL,
	"trace_id" text,
	"outcome" text NOT NULL,
	"reason_codes" jsonb NOT NULL,
	"policy_revision_id" text,
	"detail" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "policy_decision_id_created_at_pk" PRIMARY KEY("id","created_at"),
	CONSTRAINT "policy_decision_outcome_chk" CHECK ("outcome" IN ('allow','clamp','deny'))
) PARTITION BY RANGE ("created_at");--> statement-breakpoint

CREATE TABLE "usage_record" (
	"id" text NOT NULL,
	"workspace_id" text NOT NULL,
	"observation_id" text NOT NULL,
	"trace_id" text NOT NULL,
	"input_tokens" bigint,
	"output_tokens" bigint,
	"cached_tokens" bigint,
	"reasoning_tokens" bigint,
	"cache_write_tokens" bigint,
	"audio_input_tokens" bigint,
	"audio_output_tokens" bigint,
	"fidelity" text NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "usage_record_id_created_at_pk" PRIMARY KEY("id","created_at"),
	CONSTRAINT "usage_record_fidelity_chk" CHECK ("fidelity" IN ('exact','estimated','unknown'))
) PARTITION BY RANGE ("created_at");--> statement-breakpoint

CREATE TABLE "cost_ledger" (
	"id" text NOT NULL,
	"workspace_id" text NOT NULL,
	"observation_id" text,
	"trace_id" text,
	"budget_account_id" text,
	"cost_center_id" text,
	"team_id" text,
	"app_id" text,
	"virtual_key_id" text,
	"amount_microusd" bigint NOT NULL,
	"fidelity" text NOT NULL,
	"price_revision_id" text,
	"offering_id" text,
	"occurred_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "cost_ledger_id_created_at_pk" PRIMARY KEY("id","created_at"),
	CONSTRAINT "cost_ledger_fidelity_chk" CHECK ("fidelity" IN ('exact','estimated','unknown'))
) PARTITION BY RANGE ("created_at");--> statement-breakpoint

CREATE TABLE "audit_event" (
	"id" text NOT NULL,
	"workspace_id" text NOT NULL,
	"actor_kind" text NOT NULL,
	"actor_id" text,
	"action" text NOT NULL,
	"target_kind" text,
	"target_id" text,
	"before_hash" text,
	"after_hash" text,
	"request_ref" text,
	"detail" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "audit_event_id_created_at_pk" PRIMARY KEY("id","created_at"),
	CONSTRAINT "audit_actor_kind_chk" CHECK ("actor_kind" IN ('member','api_token','cli','system'))
) PARTITION BY RANGE ("created_at");--> statement-breakpoint

CREATE TABLE "usage_aggregate" (
	"workspace_id" text NOT NULL,
	"grain" text NOT NULL,
	"bucket_start" timestamp with time zone NOT NULL,
	"dims" jsonb NOT NULL,
	"requests" bigint DEFAULT 0 NOT NULL,
	"input_tokens" bigint DEFAULT 0 NOT NULL,
	"output_tokens" bigint DEFAULT 0 NOT NULL,
	"cached_tokens" bigint DEFAULT 0 NOT NULL,
	"reasoning_tokens" bigint DEFAULT 0 NOT NULL,
	"cost_microusd" bigint DEFAULT 0 NOT NULL,
	"errors" bigint DEFAULT 0 NOT NULL,
	"failovers" bigint DEFAULT 0 NOT NULL,
	"latency_ms_sum" bigint DEFAULT 0 NOT NULL,
	"latency_ms_p95" integer,
	"dims_hash" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "usage_aggregate_workspace_id_grain_bucket_start_dims_hash_pk" PRIMARY KEY("workspace_id","grain","bucket_start","dims_hash"),
	CONSTRAINT "usage_aggregate_grain_chk" CHECK ("grain" IN ('hourly','daily','monthly'))
) PARTITION BY LIST ("grain");--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 3. usage_aggregate LIST partitions: hourly detail can be pruned, monthly persists (§6.13).
-- ---------------------------------------------------------------------------
CREATE TABLE "usage_aggregate_hourly"  PARTITION OF "usage_aggregate" FOR VALUES IN ('hourly');--> statement-breakpoint
CREATE TABLE "usage_aggregate_daily"   PARTITION OF "usage_aggregate" FOR VALUES IN ('daily');--> statement-breakpoint
CREATE TABLE "usage_aggregate_monthly" PARTITION OF "usage_aggregate" FOR VALUES IN ('monthly');--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 4. Foreign keys for the recreated partitioned tables (mirror 0000).
-- ---------------------------------------------------------------------------
ALTER TABLE "budget_reservation" ADD CONSTRAINT "budget_reservation_workspace_id_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspace"("id");--> statement-breakpoint
ALTER TABLE "budget_reservation" ADD CONSTRAINT "budget_reservation_budget_account_id_budget_account_id_fk" FOREIGN KEY ("budget_account_id") REFERENCES "public"."budget_account"("id");--> statement-breakpoint
ALTER TABLE "observation_event" ADD CONSTRAINT "observation_event_workspace_id_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspace"("id");--> statement-breakpoint
ALTER TABLE "observation" ADD CONSTRAINT "observation_workspace_id_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspace"("id");--> statement-breakpoint
ALTER TABLE "trace_summary" ADD CONSTRAINT "trace_summary_workspace_id_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspace"("id");--> statement-breakpoint
ALTER TABLE "policy_decision" ADD CONSTRAINT "policy_decision_workspace_id_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspace"("id");--> statement-breakpoint
ALTER TABLE "usage_record" ADD CONSTRAINT "usage_record_workspace_id_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspace"("id");--> statement-breakpoint
ALTER TABLE "cost_ledger" ADD CONSTRAINT "cost_ledger_workspace_id_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspace"("id");--> statement-breakpoint
ALTER TABLE "audit_event" ADD CONSTRAINT "audit_event_workspace_id_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspace"("id");--> statement-breakpoint
ALTER TABLE "usage_aggregate" ADD CONSTRAINT "usage_aggregate_workspace_id_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspace"("id");--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 5. Indexes for the recreated partitioned tables (mirror 0000). On a partitioned
--    parent these become partitioned indexes that Postgres propagates to every partition.
--    Every unique index includes created_at (B1) so it is legal on the partitioned table.
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX "reservation_request_uq" ON "budget_reservation" USING btree ("budget_account_id","request_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "observation_event_dedup_uq" ON "observation_event" USING btree ("workspace_id","producer_id","idempotency_key","created_at");--> statement-breakpoint
CREATE INDEX "oe_trace_idx" ON "observation_event" USING btree ("workspace_id","trace_id","seq");--> statement-breakpoint
CREATE UNIQUE INDEX "observation_trace_uq" ON "observation" USING btree ("workspace_id","trace_id","created_at");--> statement-breakpoint
CREATE INDEX "obs_ws_time_idx" ON "observation" USING btree ("workspace_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "obs_route_time_idx" ON "observation" USING btree ("workspace_id","route_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "obs_status_time_idx" ON "observation" USING btree ("workspace_id","status","created_at" DESC NULLS LAST) WHERE status <> 'ok';--> statement-breakpoint
CREATE INDEX "obs_key_time_idx" ON "observation" USING btree ("workspace_id","virtual_key_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "obs_costcenter_idx" ON "observation" USING btree ("workspace_id","cost_center_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "policy_decision_trace_idx" ON "policy_decision" USING btree ("workspace_id","trace_id");--> statement-breakpoint
CREATE INDEX "cost_ledger_budget_idx" ON "cost_ledger" USING btree ("workspace_id","budget_account_id","occurred_at");--> statement-breakpoint
CREATE INDEX "cost_ledger_cc_idx" ON "cost_ledger" USING btree ("workspace_id","cost_center_id","occurred_at");--> statement-breakpoint
CREATE INDEX "audit_ws_time_idx" ON "audit_event" USING btree ("workspace_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "audit_target_idx" ON "audit_event" USING btree ("workspace_id","target_kind","target_id");--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 6. Partition-maintenance helper (§6.13, §20.4). Creates a monthly RANGE partition
--    for a parent given any date within the target month. Idempotent.
--    The daily maintenance job calls this a month ahead; retention drops old partitions.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION create_month_partition(p_parent text, p_month date)
RETURNS text AS $$
DECLARE
	v_start date := date_trunc('month', p_month)::date;
	v_end   date := (date_trunc('month', p_month) + interval '1 month')::date;
	v_name  text := format('%s_%s', p_parent, to_char(v_start, 'YYYYMM'));
BEGIN
	EXECUTE format(
		'CREATE TABLE IF NOT EXISTS %I PARTITION OF %I FOR VALUES FROM (%L) TO (%L)',
		v_name, p_parent, v_start, v_end
	);
	RETURN v_name;
END;
$$ LANGUAGE plpgsql;--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 7. Initial current-month partitions for each RANGE-partitioned table so the DB is
--    immediately writable. (Partition creation is a data migration per §6.16, run
--    ongoing by the maintenance job; these bootstrap the first month.)
-- ---------------------------------------------------------------------------
SELECT create_month_partition('observation_event',  CURRENT_DATE);--> statement-breakpoint
SELECT create_month_partition('observation',         CURRENT_DATE);--> statement-breakpoint
SELECT create_month_partition('trace_summary',       CURRENT_DATE);--> statement-breakpoint
SELECT create_month_partition('policy_decision',     CURRENT_DATE);--> statement-breakpoint
SELECT create_month_partition('usage_record',        CURRENT_DATE);--> statement-breakpoint
SELECT create_month_partition('cost_ledger',         CURRENT_DATE);--> statement-breakpoint
SELECT create_month_partition('audit_event',         CURRENT_DATE);--> statement-breakpoint
SELECT create_month_partition('budget_reservation',  CURRENT_DATE);--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 8. Immutability enforcement (§6.15). BEFORE UPDATE OR DELETE triggers raise
--    IMMUTABLE_ROW, except two whitelisted deltas:
--      - observation.compacted false -> true (and capture_ref null-out), all else frozen.
--      - gateway_config_revision.status active -> superseded|rolled_back, all else frozen.
--    Partition DROP/DETACH is DDL, not DML, so these triggers never fire on retention.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION forbid_mutation() RETURNS trigger AS $$
BEGIN
	RAISE EXCEPTION 'IMMUTABLE_ROW: % on %', TG_OP, TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;--> statement-breakpoint

CREATE OR REPLACE FUNCTION observation_guard_mutation() RETURNS trigger AS $$
DECLARE
	n observation := NEW;
BEGIN
	IF TG_OP = 'DELETE' THEN
		RAISE EXCEPTION 'IMMUTABLE_ROW: DELETE on observation';
	END IF;
	-- compacted may only flip false -> true
	IF NEW.compacted IS DISTINCT FROM OLD.compacted
	   AND NOT (OLD.compacted = false AND NEW.compacted = true) THEN
		RAISE EXCEPTION 'IMMUTABLE_ROW: illegal compacted transition on observation';
	END IF;
	-- capture_ref may only be nulled out (§13.6 step 3)
	IF NEW.capture_ref IS DISTINCT FROM OLD.capture_ref AND NEW.capture_ref IS NOT NULL THEN
		RAISE EXCEPTION 'IMMUTABLE_ROW: capture_ref may only be nulled on observation';
	END IF;
	-- no other column may change
	n.compacted := OLD.compacted;
	n.capture_ref := OLD.capture_ref;
	IF ROW(n.*) IS DISTINCT FROM ROW(OLD.*) THEN
		RAISE EXCEPTION 'IMMUTABLE_ROW: forbidden column change on observation';
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;--> statement-breakpoint

CREATE OR REPLACE FUNCTION config_revision_guard_mutation() RETURNS trigger AS $$
DECLARE
	n gateway_config_revision := NEW;
BEGIN
	IF TG_OP = 'DELETE' THEN
		RAISE EXCEPTION 'IMMUTABLE_ROW: DELETE on gateway_config_revision';
	END IF;
	-- status may only go active -> superseded|rolled_back
	IF NEW.status IS DISTINCT FROM OLD.status
	   AND NOT (OLD.status = 'active' AND NEW.status IN ('superseded','rolled_back')) THEN
		RAISE EXCEPTION 'IMMUTABLE_ROW: illegal status transition on gateway_config_revision';
	END IF;
	n.status := OLD.status;
	IF ROW(n.*) IS DISTINCT FROM ROW(OLD.*) THEN
		RAISE EXCEPTION 'IMMUTABLE_ROW: forbidden column change on gateway_config_revision';
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;--> statement-breakpoint

-- Generic freeze on fully-immutable tables.
CREATE TRIGGER gateway_route_revision_immutable  BEFORE UPDATE OR DELETE ON "gateway_route_revision"  FOR EACH ROW EXECUTE FUNCTION forbid_mutation();--> statement-breakpoint
CREATE TRIGGER gateway_policy_revision_immutable  BEFORE UPDATE OR DELETE ON "gateway_policy_revision"  FOR EACH ROW EXECUTE FUNCTION forbid_mutation();--> statement-breakpoint
CREATE TRIGGER provider_price_revision_immutable  BEFORE UPDATE OR DELETE ON "provider_price_revision"  FOR EACH ROW EXECUTE FUNCTION forbid_mutation();--> statement-breakpoint
CREATE TRIGGER observation_event_immutable        BEFORE UPDATE OR DELETE ON "observation_event"        FOR EACH ROW EXECUTE FUNCTION forbid_mutation();--> statement-breakpoint
CREATE TRIGGER policy_decision_immutable          BEFORE UPDATE OR DELETE ON "policy_decision"          FOR EACH ROW EXECUTE FUNCTION forbid_mutation();--> statement-breakpoint
CREATE TRIGGER audit_event_immutable              BEFORE UPDATE OR DELETE ON "audit_event"              FOR EACH ROW EXECUTE FUNCTION forbid_mutation();--> statement-breakpoint
CREATE TRIGGER cost_ledger_immutable              BEFORE UPDATE OR DELETE ON "cost_ledger"              FOR EACH ROW EXECUTE FUNCTION forbid_mutation();--> statement-breakpoint
-- Purpose-built triggers that whitelist the one allowed delta.
CREATE TRIGGER observation_immutable              BEFORE UPDATE OR DELETE ON "observation"              FOR EACH ROW EXECUTE FUNCTION observation_guard_mutation();--> statement-breakpoint
CREATE TRIGGER gateway_config_revision_immutable  BEFORE UPDATE OR DELETE ON "gateway_config_revision"  FOR EACH ROW EXECUTE FUNCTION config_revision_guard_mutation();--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 9. Row-level security (§6.16). Every tenant table gets RLS with a policy keyed on
--    manifold.workspace_id (set via `SET LOCAL` at the start of each request txn, §15.2).
--    `current_setting(..., true)` returns NULL (fail-closed) when the GUC is unset.
--    Global reference tables (canonical_model, provider_model_offering,
--    provider_price_revision, registry_field_evidence) and the workspace root are excluded.
--    job_ledger holds tenant rows AND system rows (workspace_id IS NULL). Its policy is
--    strictly workspace-scoped: a tenant GUC sees ONLY its own rows, NOT the system (NULL)
--    rows. Making the NULL path tenant-visible/writable is FAIL-OPEN (any tenant could read,
--    claim, mutate, or forge system jobs). System jobs are owned+processed by the migration
--    owner / a BYPASSRLS worker role (the same privileged seam migrations use), never by the
--    tenant-facing app role.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
	t text;
	tenant_tables text[] := ARRAY[
		'cost_center','team','member','team_member','api_token','cli_authorization',
		'gateway_installation','gateway_ingress_profile','app','action','virtual_key',
		'provider_credential','data_encryption_key','gateway_route','gateway_route_revision',
		'gateway_target','gateway_policy','gateway_policy_revision','model_entitlement',
		'request_constraint','data_handling_constraint','policy_approval','budget_account',
		'budget_allocation','budget_reservation','budget_window_state','observation_event',
		'observation','trace_summary','policy_decision','annotation','feedback_event',
		'usage_record','cost_ledger','usage_aggregate','projection_checkpoint',
		'gateway_config_revision','config_operation','audit_event','alert_rule','storage_stat'
	];
BEGIN
	FOREACH t IN ARRAY tenant_tables LOOP
		EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
		EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
		EXECUTE format(
			'CREATE POLICY %I ON %I USING (workspace_id = current_setting(''manifold.workspace_id'', true))',
			t || '_rls', t
		);
	END LOOP;
	-- job_ledger: STRICTLY tenant-scoped. System rows (workspace_id IS NULL) are deliberately
	-- NOT reachable through this policy — the old `OR workspace_id IS NULL` disjunct was
	-- fail-open (any tenant GUC could SELECT/UPDATE/DELETE system rows and INSERT NULL-workspace
	-- jobs). The single USING expression also governs INSERT/UPDATE WITH CHECK, so a tenant can
	-- neither read another tenant's/a system row nor write one with a foreign or NULL workspace.
	-- System jobs are handled by the migration owner / a BYPASSRLS worker role.
	EXECUTE 'ALTER TABLE job_ledger ENABLE ROW LEVEL SECURITY';
	EXECUTE 'ALTER TABLE job_ledger FORCE ROW LEVEL SECURITY';
	EXECUTE 'CREATE POLICY job_ledger_rls ON job_ledger USING (workspace_id = current_setting(''manifold.workspace_id'', true))';
END;
$$;--> statement-breakpoint
