import { audit } from "@/lib/audit";
import { ManifoldError, wrapInEnvelope } from "@/lib/http";
import { contractBody, contractOk, contractOptionalEmptyBody, contractQuery } from "@/lib/contracts";
import { EmptyRequest, SettingsEndpointContracts } from "@manifold/contracts";
import { runMutationGuard } from "@/lib/mutation-guard";
import { authorizeSettings } from "@/lib/settings/access";
import { notFound } from "@/lib/settings/crud";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
type Row = { id: string; slug: string; name: string; parent_id: string | null; created_at: string };
export async function PATCH(req: Request, ctx: { params: Promise<{ id: string }> }) { return mutate(req, ctx, false); }
export async function DELETE(req: Request, ctx: { params: Promise<{ id: string }> }) { return mutate(req, ctx, true); }
async function mutate(req: Request, ctx: { params: Promise<{ id: string }> }, archive: boolean): Promise<Response> { return wrapInEnvelope(async (requestId) => { contractQuery(new URL(req.url).searchParams, SettingsEndpointContracts.emptyQuery); const principal = await authorizeSettings(req, "config:write"); const { id } = await ctx.params; return runMutationGuard({ request: req, principal, requestId, handler: async (sql) => { const value = archive ? (await contractOptionalEmptyBody(req.clone(), EmptyRequest), {}) : await contractBody(req.clone(), SettingsEndpointContracts.costCenterUpdate); if (!archive && value.parentId === id) throw new ManifoldError({ status: 422, code: "VALIDATION", message: "a cost center cannot be its own parent", reasonCodes: [] }); if (value.parentId && !(await sql<{ id: string }[]>`SELECT id FROM cost_center WHERE id = ${value.parentId} AND workspace_id = ${principal.workspaceId} AND archived_at IS NULL`)[0]) throw notFound("parent cost center"); const current = (await sql<Row[]>`SELECT id, slug, name, parent_id, created_at FROM cost_center WHERE id = ${id} AND workspace_id = ${principal.workspaceId} AND archived_at IS NULL`)[0]; if (!current) throw notFound("cost center"); if (archive) { const dependent = (await sql<{ id: string }[]>`SELECT id FROM cost_center WHERE parent_id = ${id} AND workspace_id = ${principal.workspaceId} AND archived_at IS NULL UNION ALL SELECT id FROM team WHERE cost_center_id = ${id} AND workspace_id = ${principal.workspaceId} AND archived_at IS NULL LIMIT 1`)[0]; if (dependent) throw new ManifoldError({ status: 409, code: "VALIDATION", message: "move child cost centers and teams before archiving this cost center", reasonCodes: ["COST_CENTER_IN_USE"] }); await sql`UPDATE cost_center SET archived_at = now(), updated_at = now() WHERE id = ${id} AND workspace_id = ${principal.workspaceId}`; await audit(sql, principal, { action: "cost_center.archive", targetKind: "cost_center", targetId: id, requestId }); return contractOk(SettingsEndpointContracts.costCenterArchived, { data: { id, archived: true } }, requestId); } const row = (await sql<Row[]>`UPDATE cost_center SET slug = ${value.slug ?? current.slug}, name = ${value.name ?? current.name}, parent_id = ${value.parentId === undefined ? current.parent_id : value.parentId}, updated_at = now() WHERE id = ${id} AND workspace_id = ${principal.workspaceId} RETURNING id, slug, name, parent_id, created_at`)[0]!; await audit(sql, principal, { action: "cost_center.update", targetKind: "cost_center", targetId: id, requestId, detail: value }); return contractOk(SettingsEndpointContracts.costCenterResponse, { data: { id: row.id, slug: row.slug, name: row.name, parentId: row.parent_id, createdAt: row.created_at } }, requestId); } }); }); }
