"use client";

import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { CommandPalette } from "./command-palette";
import type { AppShellProps, MemberRole, ShellNavGroup, WorkspaceProfile } from "./types";
import { telemetryHref } from "@/components/telemetry/telemetry-filters";

const roleRank: Record<MemberRole, number> = { billing: -1, viewer: 0, editor: 1, admin: 2, owner: 3 };
const defaultNav: ShellNavGroup[] = [
  { label: "Gateway", items: [{ label: "Overview", href: "/" }, { label: "Routes", href: "/routes", minRole: "editor" }, { label: "Providers", href: "/providers", minRole: "editor" }, { label: "Keys", href: "/keys", minRole: "editor" }, { label: "Logs", href: "/logs" }, { label: "Usage", href: "/usage" }, { label: "Models", href: "/models" }] },
  { label: "Governance", items: [{ label: "Policies", href: "/policies", minRole: "editor", enterpriseOnly: true }, { label: "Budgets", href: "/budgets", minRole: "editor", enterpriseOnly: true }, { label: "Audit", href: "/audit", enterpriseOnly: true }] },
  { items: [{ label: "Deployments", href: "/deployments", minRole: "admin" }, { label: "Storage", href: "/storage", minRole: "admin" }, { label: "Publish", href: "/publish", minRole: "editor" }, { label: "Settings", href: "/settings", minRole: "admin" }] },
];
export function AppShell({ children, user, workspace, profile, profiles, pendingChanges = 0, nav = defaultNav, onProfileChange, onLogout, telemetrySearch }: AppShellProps) {
  const [mobileOpen, setMobileOpen] = useState(false); const [theme, setTheme] = useState<"dark" | "light">("dark");
  useEffect(() => { const stored = window.localStorage.getItem("manifold-theme") as "dark" | "light" | null; const next = stored ?? "dark"; setTheme(next); document.documentElement.dataset.theme = next; }, []);
  const changeTheme = () => { const next = theme === "dark" ? "light" : "dark"; setTheme(next); document.documentElement.dataset.theme = next; window.localStorage.setItem("manifold-theme", next); };
  const filtered = useMemo(() => nav.map((group) => ({ ...group, items: group.items.filter((item) => user.role !== "billing" && (!item.enterpriseOnly || profiles.includes("enterprise_egress")) && (!item.minRole || roleRank[user.role] >= roleRank[item.minRole])).map((item) => telemetrySearch ? { ...item, href: telemetryHref(item.href, telemetrySearch.range, telemetrySearch.profile) } : item) })).filter((group) => group.items.length), [nav, profiles, telemetrySearch, user.role]);
  const allItems = filtered.flatMap((group) => group.items);
  return <div className="shell-root"><header className="shell-topbar"><Button aria-label="Open navigation" className="shell-menu-button" onClick={() => setMobileOpen(true)} variant="ghost">☰</Button><a className="shell-brand" href="/">Manifold</a><span className="shell-workspace">{workspace.name}</span><label className="shell-profile">profile:<select aria-label="Ingress profile" onChange={(event) => onProfileChange?.(event.target.value as WorkspaceProfile)} value={profile}>{profiles.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><div className="shell-topbar-spacer" /><a className="shell-publish" href="/publish">◆ Publish{pendingChanges ? <span>{pendingChanges}</span> : null}</a><CommandPalette items={allItems} /><Button aria-label={`Switch to ${theme === "dark" ? "light" : "dark"} theme`} className="shell-theme" onClick={changeTheme} variant="ghost">{theme === "dark" ? "☀" : "◐"}</Button><button className="shell-user" onClick={onLogout} type="button"><span className="shell-avatar">{user.initials ?? user.name.slice(0, 2).toUpperCase()}</span><span>{user.name}</span><span>Log out</span></button></header><aside aria-label="Main navigation" className={`shell-rail ${mobileOpen ? "is-open" : ""}`}><div className="shell-mobile-header"><strong>Navigation</strong><Button onClick={() => setMobileOpen(false)} variant="ghost">Close</Button></div><label className="shell-mobile-profile"><span>Ingress profile</span><select aria-label="Mobile ingress profile" onChange={(event) => onProfileChange?.(event.target.value as WorkspaceProfile)} value={profile}>{profiles.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><Nav groups={filtered} onNavigate={() => setMobileOpen(false)} /></aside>{mobileOpen ? <button aria-label="Close navigation" className="shell-scrim" onClick={() => setMobileOpen(false)} /> : null}<main className="shell-main">{children}</main></div>;
}
function Nav({ groups, onNavigate }: { groups: ShellNavGroup[]; onNavigate: () => void }) { const path = typeof window === "undefined" ? "" : window.location.pathname; return <nav>{groups.map((group, index) => <section className="shell-nav-group" key={group.label ?? index}>{group.label ? <h2>{group.label}</h2> : null}{group.items.map((item) => <a aria-current={path === item.href ? "page" : undefined} href={item.href} key={item.href} onClick={onNavigate}>{item.label}</a>)}</section>)}</nav>; }
export type { AppShellProps, ShellNavGroup, ShellNavItem } from "./types";
