import { audit } from "@/lib/audit";
import { withWorkspace } from "@/lib/db";
import { requireMutationIdempotencyKey, runMutationGuard } from "@/lib/mutation-guard";
import { ManifoldError, wrapInEnvelope } from "@/lib/http";
import { contractBody, contractOk, contractQuery } from "@/lib/contracts";
import { SettingsEndpointContracts } from "@manifold/contracts";
import { authorizeSettings } from "@/lib/settings/access";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
type Workspace = { id: string; slug: string; name: string; region: string; storage_ceiling_bytes: string; storage_warn_pct: number; storage_high_pct: number; storage_crit_pct: number; created_at: string; updated_at: string };
function serialize(row: Workspace) { return { id: row.id, slug: row.slug, name: row.name, region: row.region, storagePolicy: { ceilingBytes: row.storage_ceiling_bytes, warnPct: row.storage_warn_pct, highPct: row.storage_high_pct, critPct: row.storage_crit_pct }, createdAt: row.created_at, updatedAt: row.updated_at }; }
export async function GET(req: Request) { return wrapInEnvelope(async (requestId) => { contractQuery(new URL(req.url).searchParams, SettingsEndpointContracts.emptyQuery); const principal = await authorizeSettings(req, "config:read"); const row = await withWorkspace(principal.workspaceId, async (sql) => (await sql<Workspace[]>`SELECT id, slug, name, region, storage_ceiling_bytes, storage_warn_pct, storage_high_pct, storage_crit_pct, created_at, updated_at FROM workspace WHERE id = ${principal.workspaceId} LIMIT 1`)[0]); if (!row) throw new ManifoldError({ status: 404, code: "NOT_FOUND", message: "workspace not found", reasonCodes: [] }); return contractOk(SettingsEndpointContracts.workspaceResponse, { data: serialize(row) }, requestId); }); }
export async function PATCH(req: Request) { return wrapInEnvelope(async (requestId) => { contractQuery(new URL(req.url).searchParams, SettingsEndpointContracts.emptyQuery); const principal = await authorizeSettings(req, "config:write"); requireMutationIdempotencyKey(req); const body = await contractBody(req.clone(), SettingsEndpointContracts.workspace); const name = body.name; return runMutationGuard({ request: req, principal, requestId, rateLimit: { limit: 20, windowMs: 60_000 }, handler: async (sql) => { const row = await (async () => { const current = (await sql<Workspace[]>`SELECT id, slug, name, region, storage_ceiling_bytes, storage_warn_pct, storage_high_pct, storage_crit_pct, created_at, updated_at FROM workspace WHERE id = ${principal.workspaceId} FOR UPDATE`)[0]; if (!current) return null; const updated = (await sql<Workspace[]>`UPDATE workspace SET name = ${name}, updated_at = now() WHERE id = ${principal.workspaceId} RETURNING id, slug, name, region, storage_ceiling_bytes, storage_warn_pct, storage_high_pct, storage_crit_pct, created_at, updated_at`)[0]; await audit(sql, principal, { action: "workspace.update", targetKind: "workspace", targetId: principal.workspaceId, requestId, detail: { name } }); return updated; })(); if (!row) throw new ManifoldError({ status: 404, code: "NOT_FOUND", message: "workspace not found", reasonCodes: [] }); return contractOk(SettingsEndpointContracts.workspaceResponse, { data: serialize(row) }, requestId); }}); }); }
