import { authorize } from "@/lib/auth";
import { withWorkspace } from "@/lib/db";
import { ok, wrapInEnvelope } from "@/lib/http";
import { contractOk, contractQuery } from "@/lib/contracts";
import { ModelsApi } from "@manifold/contracts";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

interface Row { id: string; canonical_model_id: string; canonical_slug: string; display_name: string; family: string | null; modality_in: unknown; modality_out: unknown; open_weights: boolean | null; source: string; provider: string; provider_model_id: string; endpoint_kinds: unknown; adapter_revision: string; context_limit_tokens: string | null; output_limit_tokens: string | null; capabilities: unknown; region: string | null; price_revision_id: string | null; input_per_mtok_microusd: string | null; output_per_mtok_microusd: string | null; cache_read_per_mtok_microusd: string | null; cache_write_per_mtok_microusd: string | null; reasoning_per_mtok_microusd: string | null; audio_in_per_mtok_microusd: string | null; audio_out_per_mtok_microusd: string | null; price_fidelity: string | null; price_catalog_revision: string | null; effective_from: string | null; routable: boolean; }
export async function GET(req: Request): Promise<Response> { return wrapInEnvelope(async (requestId) => { const { limit, cursor, provider, endpointKind, query, routable, family, priceFidelity } = contractQuery(new URL(req.url).searchParams, ModelsApi.listQuery); const principal = await authorize(req, "registry:read"); const rows = await withWorkspace(principal.workspaceId, (sql) => sql<Row[]>`
  SELECT o.id, o.canonical_model_id, c.canonical_slug, c.display_name, c.family, c.modality_in, c.modality_out, c.open_weights, c.source, o.provider, o.provider_model_id, o.endpoint_kinds, o.adapter_revision, o.context_limit_tokens::text, o.output_limit_tokens::text, o.capabilities, o.region, p.id AS price_revision_id, p.input_per_mtok_microusd::text, p.output_per_mtok_microusd::text, p.cache_read_per_mtok_microusd::text, p.cache_write_per_mtok_microusd::text, p.reasoning_per_mtok_microusd::text, p.audio_in_per_mtok_microusd::text, p.audio_out_per_mtok_microusd::text, p.fidelity AS price_fidelity, p.catalog_revision AS price_catalog_revision, p.effective_from, EXISTS (SELECT 1 FROM provider_credential pc WHERE pc.workspace_id = ${principal.workspaceId} AND pc.provider = o.provider AND pc.status = 'valid' AND pc.revoked_at IS NULL) AS routable
  FROM provider_model_offering o JOIN canonical_model c ON c.id = o.canonical_model_id
  LEFT JOIN LATERAL (
    SELECT p.* FROM provider_price_revision p
    WHERE p.offering_id = o.id
      AND (p.workspace_id = ${principal.workspaceId} OR (p.workspace_id IS NULL AND p.id = o.active_price_revision_id))
    ORDER BY CASE WHEN p.workspace_id = ${principal.workspaceId} THEN 0 ELSE 1 END, p.effective_from DESC, p.id DESC
    LIMIT 1
  ) p ON true
  WHERE EXISTS (SELECT 1 FROM workspace w WHERE w.id = ${principal.workspaceId}) AND (${cursor}::text IS NULL OR o.id < ${cursor}) AND (${provider}::text IS NULL OR o.provider = ${provider}) AND (${endpointKind}::text IS NULL OR o.endpoint_kinds ? ${endpointKind}) AND (${query}::text IS NULL OR c.canonical_slug ILIKE '%' || ${query} || '%' OR c.display_name ILIKE '%' || ${query} || '%') AND (${family}::text IS NULL OR c.family = ${family}) AND (${priceFidelity}::text IS NULL OR (${priceFidelity} = 'unknown' AND (p.id IS NULL OR p.fidelity IS NULL OR p.fidelity = 'unknown')) OR (${priceFidelity} <> 'unknown' AND p.fidelity = ${priceFidelity})) AND (${routable}::text IS NULL OR (EXISTS (SELECT 1 FROM provider_credential pc WHERE pc.workspace_id = ${principal.workspaceId} AND pc.provider = o.provider AND pc.status = 'valid' AND pc.revoked_at IS NULL)) = (${routable} = 'true'))
  ORDER BY o.id DESC LIMIT ${limit + 1}`);
  const data = rows.slice(0, limit).map((r) => ({ id: r.id, canonicalModel: { id: r.canonical_model_id, slug: r.canonical_slug, displayName: r.display_name, family: r.family, modalityIn: r.modality_in, modalityOut: r.modality_out, openWeights: r.open_weights, source: r.source }, provider: r.provider, providerModelId: r.provider_model_id, endpointKinds: r.endpoint_kinds, adapterRevision: r.adapter_revision, capabilities: r.capabilities, limits: { contextTokens: r.context_limit_tokens, outputTokens: r.output_limit_tokens }, region: r.region, routable: r.routable, activePrice: r.price_revision_id ? { id: r.price_revision_id, fidelity: r.price_fidelity, effectiveFrom: r.effective_from, source: r.price_fidelity === "operator_override" ? "operator_override" : r.price_catalog_revision ?? r.source, currency: "USD", unit: "per_mtok", inputPerMtokMicrousd: r.input_per_mtok_microusd, outputPerMtokMicrousd: r.output_per_mtok_microusd, cacheReadPerMtokMicrousd: r.cache_read_per_mtok_microusd, cacheWritePerMtokMicrousd: r.cache_write_per_mtok_microusd, reasoningPerMtokMicrousd: r.reasoning_per_mtok_microusd, audioInPerMtokMicrousd: r.audio_in_per_mtok_microusd, audioOutPerMtokMicrousd: r.audio_out_per_mtok_microusd } : null })); return contractOk(ModelsApi.listResponse, { data, nextCursor: rows.length > limit ? data.at(-1)?.id ?? null : null }, requestId); }); }
