"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { EmptyState, PageFrame } from "@/components/console/page-frame";
import { AlertBanner } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, Skeleton } from "@/components/ui/card";
import { Input, Select } from "@/components/ui/field";
import { Sheet } from "@/components/ui/overlay";
import { StatusBadge } from "@/components/ui/status";
import { useToast } from "@/components/ui/toast";
import { apiRequest, ControlPlaneApiError } from "@/lib/api-client";
import { formatAmount, formatDate, formatNumber, scopeLabel } from "./budget-format";
import type { Budget, BudgetDetailResponse, Context, Key, Page } from "./budget-types";

function errorMessage(error: unknown) { return error instanceof ControlPlaneApiError ? error.payload.remediation ?? error.message : error instanceof Error ? error.message : "Unable to load this budget"; }

export function BudgetDetail({ budgetId }: { budgetId: string }) {
  const toast = useToast(); const [budget, setBudget] = useState<BudgetDetailResponse | null>(null); const [context, setContext] = useState<Context | null>(null); const [keys, setKeys] = useState<Key[] | null>(null); const [error, setError] = useState<string | null>(null); const [allocateOpen, setAllocateOpen] = useState(false);
  const load = useCallback(async () => { setError(null); try { const [detail, nextContext, nextKeys] = await Promise.all([apiRequest<BudgetDetailResponse>(`/budgets/${budgetId}`), context ? Promise.resolve(context) : apiRequest<Context>("/context"), keys ? Promise.resolve(keys) : apiRequest<Page<Key>>("/keys").then((result) => result.data).catch(() => null)]); setBudget(detail); setContext(nextContext); setKeys(nextKeys); } catch (caught) { setError(errorMessage(caught)); setBudget(null); } }, [budgetId, context, keys]);
  useEffect(() => { void load(); }, [load]);
  return <PageFrame actions={<div className="console-actions"><a className="cp-button" href="/budgets">All budgets</a><Button disabled={!budget} onClick={() => setAllocateOpen(true)} variant="primary">Allocate to child</Button></div>} description="Inspect staged cap consumption, forecast, allocations, reservations, and scoped alerts" title="Budget detail">
    <div className="console-stack">{error ? <AlertBanner title="Budget unavailable" tone="down">{error} <Button onClick={() => void load()} variant="outline">Retry</Button></AlertBanner> : null}{!budget && !error ? <DetailSkeleton /> : null}{budget ? <>
      <AlertBanner title="Staged enforcement" tone="verifying">This account is desired configuration only. <a href="/publish" style={{ color: "var(--accent)" }}>Open Publish</a> before gateway enforcement can change.</AlertBanner>
      <Card className="console-card-body"><div className="console-grid"><Metric label="Scope" value={scopeLabel(budget.scope, context, keys)} /><Metric label="Cap" value={formatAmount(budget.limitAmount, budget.unit)} /><Metric label="Enforcement" value={<StatusBadge status={budget.enforcement === "hard" ? "verifying" : "idle"}>{budget.enforcement}</StatusBadge>} /><Metric label="Window" value={budget.window.replaceAll("_", " ")} /><Metric label="State" value={<StatusBadge status={budget.overBudget ? "down" : "verifying"}>{budget.overBudget ? "Over cap" : "Staged"}</StatusBadge>} /></div></Card>
      <div className="console-grid"><Card className="console-card-body"><div className="console-kpi-label">Current counters</div><div className="console-grid" style={{ marginTop: 14 }}><Metric label="Committed" value={formatAmount(budget.counters.committed, budget.unit)} /><Metric label="Reserved" value={formatAmount(budget.counters.reserved, budget.unit)} /><Metric label="Current" value={formatAmount(budget.counters.current, budget.unit)} /></div></Card><ForecastCard budget={budget} /></div>
      <Allocations budget={budget} context={context} keys={keys} /><Reservations budget={budget} /><Alerts budget={budget} context={context} keys={keys} />
      <Card className="console-card-body"><div className="console-kpi-label">Schema limits</div><p className="console-muted" style={{ fontSize: 13, marginBottom: 0 }}>The current schema has no budget revision history and no durable Idempotency-Key response store. Allocation identity is immutable once created. The UI does not claim revision or replay behavior that is not stored.</p></Card>
      <AllocateSheet budget={budget} context={context} keys={keys} onClose={() => setAllocateOpen(false)} onCreated={() => { setAllocateOpen(false); toast("Allocation staged for Publish", "verifying"); void load(); }} open={allocateOpen} />
    </> : null}</div>
  </PageFrame>;
}

function Metric({ label, value }: { label: string; value: React.ReactNode }) { return <div><div className="console-kpi-label">{label}</div><div className="console-mono" style={{ fontSize: 14, marginTop: 7 }}>{value}</div></div>; }
function DetailSkeleton() { return <div className="console-stack"><Skeleton style={{ height: 98 }} /><Skeleton style={{ height: 150 }} /><Skeleton style={{ height: 180 }} /></div>; }
function ForecastCard({ budget }: { budget: BudgetDetailResponse }) { const forecast = budget.burn; return <Card className="console-card-body"><div className="console-kpi-label">Burn and forecast</div>{forecast.status === "unavailable" ? <EmptyState description={forecast.reason ?? "No window boundary is available for this forecast"} title="Forecast unavailable" /> : <div className="console-grid" style={{ marginTop: 14 }}><Metric label="Run rate" value={`${formatNumber(forecast.burnRatePerDay)} ${budget.unit === "tokens" ? "tokens" : "micro-USD"} per day`} /><Metric label="Forecast" value={forecast.forecastAmount ? formatAmount(forecast.forecastAmount, budget.unit) : "Unavailable"} /><Metric label="Window end" value={formatDate(forecast.windowEnd ?? null)} /></div>}</Card>; }
function Allocations({ budget, context, keys }: { budget: BudgetDetailResponse; context: Context | null; keys: Key[] | null }) { return <Card className="console-card-body"><div className="console-kpi-label">Child allocations</div>{budget.allocations.length === 0 ? <EmptyState description="Create an allocation for a direct child budget when it needs a reserved allowance" title="No child allocations" /> : <div className="console-table-wrap" style={{ marginTop: 12 }}><table className="console-table"><thead><tr><th>Child</th><th>Allowance</th><th>Window</th><th>Created</th></tr></thead><tbody>{budget.allocations.map((item) => <tr key={item.id}><td>{scopeLabel(item.childScope, context, keys)}</td><td className="console-mono">{formatAmount(item.reservedAllowance, budget.unit)}</td><td>{item.window.replaceAll("_", " ")}</td><td>{formatDate(item.createdAt)}</td></tr>)}</tbody></table></div>}</Card>; }
function Reservations({ budget }: { budget: BudgetDetailResponse }) { return <Card className="console-card-body"><div className="console-kpi-label">Live reservations</div>{budget.reservations.length === 0 ? <EmptyState description="No reservation records are available for this account" title="No reservations" /> : <div className="console-table-wrap" style={{ marginTop: 12 }}><table className="console-table"><thead><tr><th>Request</th><th>Reserved</th><th>Status</th><th>Expires</th></tr></thead><tbody>{budget.reservations.map((item) => <tr key={`${item.id}-${item.createdAt}`}><td className="console-mono">{item.requestId}</td><td className="console-mono">{formatAmount(budget.unit === "tokens" ? item.reservedTokens ?? "0" : item.reservedMicrousd, budget.unit)}</td><td><StatusBadge status={item.status === "reserved" ? "verifying" : item.status === "committed" ? "up" : "idle"}>{item.status}</StatusBadge></td><td>{formatDate(item.expiresAt)}</td></tr>)}</tbody></table></div>}</Card>; }
function Alerts({ budget, context, keys }: { budget: BudgetDetailResponse; context: Context | null; keys: Key[] | null }) { return <Card className="console-card-body"><div className="console-kpi-label">Scoped alert rules</div><p className="console-muted" style={{ fontSize: 13 }}>Alert rules are matched by the account scope and window because the current schema has no budget-account reference.</p>{budget.alerts.length === 0 ? <EmptyState description="No alert rules match this scope and window" title="No scoped alerts" /> : <div className="console-table-wrap"><table className="console-table"><thead><tr><th>Scope</th><th>Metric</th><th>Threshold</th><th>State</th></tr></thead><tbody>{budget.alerts.map((item) => <tr key={item.id}><td>{scopeLabel(item.scope, context, keys)}</td><td>{item.metric}</td><td className="console-mono">{item.threshold}</td><td><StatusBadge status={item.status === "active" ? "up" : "idle"}>{item.status}</StatusBadge></td></tr>)}</tbody></table></div>}</Card>; }
function AllocateSheet({ budget, context, keys, onClose, onCreated, open }: { budget: BudgetDetailResponse; context: Context | null; keys: Key[] | null; onClose: () => void; onCreated: () => void; open: boolean }) { const [children, setChildren] = useState<Budget[]>([]); const [childId, setChildId] = useState(""); const [amount, setAmount] = useState(""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); useEffect(() => { if (!open) return; apiRequest<Page<Budget>>(`/budgets?limit=100`).then((result) => { const direct = result.data.filter((item) => item.parentId === budget.id && item.unit === budget.unit && item.window === budget.window); setChildren(direct); setChildId(direct[0]?.id ?? ""); }).catch((caught) => setError(errorMessage(caught))); }, [budget.id, budget.unit, budget.window, open]); const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); if (!childId || !/^\d+$/.test(amount)) { setError("Select a child and enter a non-negative whole-number allowance"); return; } setSaving(true); try { await apiRequest(`/budgets/${budget.id}/allocate`, { method: "POST", body: { childId, reservedAllowance: amount } }); onCreated(); } catch (caught) { setError(errorMessage(caught)); } finally { setSaving(false); } }; return <Sheet onClose={onClose} open={open} title="Allocate to child"><form className="console-form" onSubmit={submit}><p className="console-muted" style={{ margin: 0 }}>Allocations are immutable in the current schema. A matching allocation cannot be edited or revised.</p>{error ? <AlertBanner title="Allocation could not be staged" tone="down">{error}</AlertBanner> : null}<label className="console-field"><span>Direct child budget</span><Select onChange={(event) => setChildId(event.target.value)} value={childId}><option value="">Select child</option>{children.map((item) => <option key={item.id} value={item.id}>{scopeLabel(item.scope, context, keys)}</option>)}</Select></label>{children.length === 0 ? <AlertBanner title="No compatible child budgets" tone="verifying">Create a direct child with the same unit and window before allocating.</AlertBanner> : null}<label className="console-field"><span>Reserved allowance</span><Input inputMode="numeric" onChange={(event) => setAmount(event.target.value)} required value={amount} /></label><div className="console-actions"><Button onClick={onClose}>Cancel</Button><Button disabled={saving || !children.length} type="submit" variant="primary">{saving ? "Staging allocation" : "Stage allocation"}</Button></div></form></Sheet>; }
