// Composite config-authoring context. It deliberately requires only config:read: callers need not
// carry every underlying picker scope, and every query remains explicitly workspace-predicated.
import { authorize } from "@/lib/auth";
import { withWorkspace } from "@/lib/db";
import { wrapInEnvelope } from "@/lib/http";
import { contractOk } from "@/lib/contracts";
import { ContextResponse } from "@manifold/contracts";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
type Workspace = { id: string; slug: string; name: string; region: string };
type Installation = { id: string; name: string; edition: string; disabled_at: string | null; last_seen_at: string | null };
type Profile = { id: string; installation_id: string; hostname: string; mode: string; network_exposure: string; disabled_at: string | null };
type App = { id: string; slug: string; name: string; status: string };
type Action = { id: string; app_id: string; slug: string; name: string | null; source: string };
type Team = { id: string; slug: string; name: string; cost_center_id: string | null };
type CostCenter = { id: string; slug: string; name: string; parent_id: string | null };
export async function GET(req: Request): Promise<Response> { return wrapInEnvelope(async (requestId) => { const principal = await authorize(req, "config:read"); const result = await withWorkspace(principal.workspaceId, async (sql) => ({ workspace: (await sql<Workspace[]>`SELECT id, slug, name, region FROM workspace WHERE id = ${principal.workspaceId} LIMIT 1`)[0] ?? null, installations: await sql<Installation[]>`SELECT id, name, edition, disabled_at, last_seen_at FROM gateway_installation WHERE workspace_id = ${principal.workspaceId} ORDER BY name`, profiles: await sql<Profile[]>`SELECT id, installation_id, hostname, mode, network_exposure, disabled_at FROM gateway_ingress_profile WHERE workspace_id = ${principal.workspaceId} ORDER BY hostname`, apps: await sql<App[]>`SELECT id, slug, name, status FROM app WHERE workspace_id = ${principal.workspaceId} AND archived_at IS NULL ORDER BY name`, actions: await sql<Action[]>`SELECT id, app_id, slug, name, source FROM action WHERE workspace_id = ${principal.workspaceId} AND archived_at IS NULL ORDER BY app_id, slug`, teams: await sql<Team[]>`SELECT id, slug, name, cost_center_id FROM team WHERE workspace_id = ${principal.workspaceId} AND archived_at IS NULL ORDER BY name`, costCenters: await sql<CostCenter[]>`SELECT id, slug, name, parent_id FROM cost_center WHERE workspace_id = ${principal.workspaceId} AND archived_at IS NULL ORDER BY name` })); return contractOk(ContextResponse, { workspace: result.workspace ? { id: result.workspace.id, slug: result.workspace.slug, name: result.workspace.name, region: result.workspace.region } : null, installations: result.installations.map((i) => ({ id: i.id, name: i.name, edition: i.edition, lastSeenAt: i.last_seen_at, status: i.disabled_at ? "disabled" : "active", profiles: result.profiles.filter((p) => p.installation_id === i.id).map((p) => ({ id: p.id, hostname: p.hostname, mode: p.mode, networkExposure: p.network_exposure, available: !i.disabled_at && !p.disabled_at, status: p.disabled_at ? "disabled" : "active" })) })), apps: result.apps.map((a) => ({ id: a.id, slug: a.slug, name: a.name, status: a.status, actions: result.actions.filter((x) => x.app_id === a.id).map((x) => ({ id: x.id, slug: x.slug, name: x.name, source: x.source })) })), teams: result.teams.map((t) => ({ id: t.id, slug: t.slug, name: t.name, costCenterId: t.cost_center_id })), costCenters: result.costCenters.map((c) => ({ id: c.id, slug: c.slug, name: c.name, parentId: c.parent_id })), profileAvailability: result.profiles.map((p) => { const installation = result.installations.find((i) => i.id === p.installation_id); return { profileId: p.id, installationId: p.installation_id, available: !p.disabled_at && !installation?.disabled_at }; }) }, requestId); }); }
