import { audit } from "@/lib/audit";
import { ManifoldError, wrapInEnvelope } from "@/lib/http";
import { contractBody, contractOk, contractOptionalEmptyBody, contractQuery } from "@/lib/contracts";
import { EmptyRequest, SettingsEndpointContracts } from "@manifold/contracts";
import { runMutationGuard } from "@/lib/mutation-guard";
import { authorizeSettings } from "@/lib/settings/access";
import { notFound } from "@/lib/settings/crud";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
type Row = { id: string; slug: string; name: string; cost_center_id: string | null; created_at: string };
export async function PATCH(req: Request, ctx: { params: Promise<{ id: string }> }) { return mutate(req, ctx, false); }
export async function DELETE(req: Request, ctx: { params: Promise<{ id: string }> }) { return mutate(req, ctx, true); }
async function mutate(req: Request, ctx: { params: Promise<{ id: string }> }, archive: boolean): Promise<Response> { return wrapInEnvelope(async (requestId) => { contractQuery(new URL(req.url).searchParams, SettingsEndpointContracts.emptyQuery); const principal = await authorizeSettings(req, "config:write"); const { id } = await ctx.params; return runMutationGuard({ request: req, principal, requestId, handler: async (sql) => { const value = archive ? (await contractOptionalEmptyBody(req.clone(), EmptyRequest), {}) : await contractBody(req.clone(), SettingsEndpointContracts.teamUpdate); if (value.costCenterId && !(await sql<{ id: string }[]>`SELECT id FROM cost_center WHERE id = ${value.costCenterId} AND workspace_id = ${principal.workspaceId} AND archived_at IS NULL`)[0]) throw notFound("cost center"); const current = (await sql<Row[]>`SELECT id, slug, name, cost_center_id, created_at FROM team WHERE id = ${id} AND workspace_id = ${principal.workspaceId} AND archived_at IS NULL`)[0]; if (!current) throw notFound("team"); if (archive) { const used = (await sql<{ id: string }[]>`SELECT id FROM virtual_key WHERE team_id = ${id} AND workspace_id = ${principal.workspaceId} AND revoked_at IS NULL LIMIT 1`)[0]; if (used) throw new ManifoldError({ status: 409, code: "VALIDATION", message: "revoke or reassign active keys before archiving this team", reasonCodes: ["TEAM_IN_USE"] }); await sql`UPDATE team SET archived_at = now(), updated_at = now() WHERE id = ${id} AND workspace_id = ${principal.workspaceId}`; await audit(sql, principal, { action: "team.archive", targetKind: "team", targetId: id, requestId }); return contractOk(SettingsEndpointContracts.teamArchived, { data: { id, archived: true } }, requestId); } const row = (await sql<Row[]>`UPDATE team SET slug = ${value.slug ?? current.slug}, name = ${value.name ?? current.name}, cost_center_id = ${value.costCenterId === undefined ? current.cost_center_id : value.costCenterId}, updated_at = now() WHERE id = ${id} AND workspace_id = ${principal.workspaceId} RETURNING id, slug, name, cost_center_id, created_at`)[0]!; await audit(sql, principal, { action: "team.update", targetKind: "team", targetId: id, requestId, detail: value }); return contractOk(SettingsEndpointContracts.teamResponse, { data: { id: row.id, slug: row.slug, name: row.name, costCenterId: row.cost_center_id, createdAt: row.created_at } }, requestId); } }); }); }
