import { authorize } from "@/lib/auth";
import { withWorkspace } from "@/lib/db";
import { wrapInEnvelope } from "@/lib/http";
import { contractOk } from "@/lib/contracts";
import { ControlPlaneContracts } from "@manifold/contracts";
import { profilePublished, TRUSTED_HOST_INVARIANT } from "@/app/api/v1/deployments/_lib";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
type Row = { id: string; installation_id: string; hostname: string; mode: string; network_exposure: string; policy_revision_id: string | null; default_route_set: unknown; disabled_at: string | null; installation_disabled_at: string | null; active_snapshot: unknown; created_at: string };
function page(req: Request) { const u = new URL(req.url); const n = Number(u.searchParams.get("limit") ?? "50"); return { limit: Number.isFinite(n) ? Math.min(Math.max(Math.floor(n), 1), 100) : 50, cursor: u.searchParams.get("cursor"), installationId: u.searchParams.get("installationId") }; }
export async function GET(req: Request): Promise<Response> { return wrapInEnvelope(async (requestId) => { const principal = await authorize(req, "deployments:read"); const { limit, cursor, installationId } = page(req); const rows = await withWorkspace(principal.workspaceId, (sql) => sql<Row[]>`SELECT p.id, p.installation_id, p.hostname, p.mode, p.network_exposure, p.policy_revision_id, p.default_route_set, p.disabled_at, i.disabled_at AS installation_disabled_at, active.snapshot AS active_snapshot, p.created_at FROM gateway_ingress_profile p JOIN gateway_installation i ON i.id = p.installation_id AND i.workspace_id = ${principal.workspaceId} LEFT JOIN gateway_config_revision active ON active.installation_id = p.installation_id AND active.workspace_id = ${principal.workspaceId} AND active.status = 'active' WHERE p.workspace_id = ${principal.workspaceId} AND (${installationId}::text IS NULL OR p.installation_id = ${installationId}) AND (${cursor}::text IS NULL OR p.id < ${cursor}) ORDER BY p.id DESC LIMIT ${limit + 1}`); const data = rows.slice(0, limit).map((p) => { const published = profilePublished(p.active_snapshot, p.hostname, p.id); return { id: p.id, installationId: p.installation_id, hostname: p.hostname, mode: p.mode, networkExposure: p.network_exposure, policyRevisionId: p.policy_revision_id, defaultRouteSet: p.default_route_set, published, bindingStatus: published ? "published" : "draft", available: !p.disabled_at && !p.installation_disabled_at && published, status: p.disabled_at ? "disabled" : "active", trustedHostInvariant: TRUSTED_HOST_INVARIANT, createdAt: p.created_at }; }); return contractOk(ControlPlaneContracts.profiles.list, { data, nextCursor: rows.length > limit ? data.at(-1)?.id ?? null : null, trustedHostInvariant: TRUSTED_HOST_INVARIANT }, requestId); }); }
