import { withWorkspace } from "@/lib/db";
import { ManifoldError, wrapInEnvelope } from "@/lib/http";
import { contractBody, contractOk, contractQuery } from "@/lib/contracts";
import { SettingsEndpointContracts } from "@manifold/contracts";
import { authorizeSettings } from "@/lib/settings/access";
import { audit } from "@/lib/audit";
import { genId } from "@/lib/ids";
import { runMutationGuard } from "@/lib/mutation-guard";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
type App = { id: string; slug: string; name: string; status: string; default_capture_policy: unknown; created_at: string };
type Action = { id: string; app_id: string; slug: string; name: string | null; source: string; created_at: string };
export async function GET(req: Request) { return wrapInEnvelope(async (requestId) => { const { cursor, limit } = contractQuery(new URL(req.url).searchParams, SettingsEndpointContracts.pageQuery); const principal = await authorizeSettings(req, "config:read"); const result = await withWorkspace(principal.workspaceId, async (sql) => ({ apps: await sql<App[]>`SELECT id, slug, name, status, default_capture_policy, created_at FROM app WHERE workspace_id = ${principal.workspaceId} AND archived_at IS NULL AND (${cursor}::text IS NULL OR id < ${cursor}) ORDER BY id DESC LIMIT ${limit + 1}`, actions: await sql<Action[]>`SELECT id, app_id, slug, name, source, created_at FROM action WHERE workspace_id = ${principal.workspaceId} AND archived_at IS NULL ORDER BY app_id, slug` })); const data = result.apps.slice(0, limit).map((app) => ({ id: app.id, slug: app.slug, name: app.name, status: app.status, defaultCapturePolicy: app.default_capture_policy, createdAt: app.created_at, actions: result.actions.filter((action) => action.app_id === app.id).map((action) => ({ id: action.id, slug: action.slug, name: action.name, source: action.source, createdAt: action.created_at })) })); return contractOk(SettingsEndpointContracts.lists.app, { data, nextCursor: result.apps.length > limit ? data.at(-1)?.id ?? null : null }, requestId); }); }
export async function POST(req: Request) { return wrapInEnvelope(async (requestId) => { contractQuery(new URL(req.url).searchParams, SettingsEndpointContracts.emptyQuery); const principal = await authorizeSettings(req, "config:write"); return runMutationGuard({ request: req, principal, requestId, handler: async (sql) => { const body = await contractBody(req, SettingsEndpointContracts.app); const value = { slug: body.slug, name: body.name, defaultCapturePolicy: body.defaultCapturePolicy ?? {} }; if (!value.defaultCapturePolicy || typeof value.defaultCapturePolicy !== "object" || Array.isArray(value.defaultCapturePolicy)) throw new ManifoldError({ status: 422, code: "VALIDATION", message: "defaultCapturePolicy must be an object", reasonCodes: [] }); const id = genId("app"); const row = (await sql<App[]>`INSERT INTO app (id, workspace_id, slug, name, default_capture_policy) VALUES (${id}, ${principal.workspaceId}, ${value.slug}, ${value.name}, ${sql.json(value.defaultCapturePolicy as never)}) RETURNING id, slug, name, status, default_capture_policy, created_at`)[0]!; await audit(sql, principal, { action: "app.create", targetKind: "app", targetId: id, requestId, detail: value }); return contractOk(SettingsEndpointContracts.appCreateResponse, { data: { id: row.id, slug: row.slug, name: row.name, status: row.status, defaultCapturePolicy: row.default_capture_policy, createdAt: row.created_at, actions: [] } }, requestId, 201); } }); }); }
