import { withWorkspace } from "@/lib/db";
import { ManifoldError, wrapInEnvelope } from "@/lib/http";
import { contractBody, contractOk, contractQuery } from "@/lib/contracts";
import { SettingsEndpointContracts } from "@manifold/contracts";
import { authorizeSettings } from "@/lib/settings/access";
import { audit } from "@/lib/audit";
import { genId } from "@/lib/ids";
import { runMutationGuard } from "@/lib/mutation-guard";
import { enforceRoleCeiling } from "@/lib/settings/crud";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
type Row = { id: string; email: string; name: string | null; role: string; disabled_at: string | null; created_at: string };
export async function GET(req: Request) { return wrapInEnvelope(async (requestId) => { const { cursor, limit } = contractQuery(new URL(req.url).searchParams, SettingsEndpointContracts.pageQuery); const principal = await authorizeSettings(req, "config:read"); const rows = await withWorkspace(principal.workspaceId, (sql) => sql<Row[]>`SELECT id, email, name, role, disabled_at, created_at FROM member WHERE workspace_id = ${principal.workspaceId} AND (${cursor}::text IS NULL OR id < ${cursor}) ORDER BY id DESC LIMIT ${limit + 1}`); const data = rows.slice(0, limit).map((row) => ({ id: row.id, email: row.email, name: row.name, role: row.role, status: row.disabled_at ? "disabled" : "active", createdAt: row.created_at })); return contractOk(SettingsEndpointContracts.lists.member, { data, nextCursor: rows.length > limit ? data.at(-1)?.id ?? null : null }, requestId); }); }
export async function POST(req: Request) { return wrapInEnvelope(async (requestId) => { contractQuery(new URL(req.url).searchParams, SettingsEndpointContracts.emptyQuery); const principal = await authorizeSettings(req, "config:write"); return runMutationGuard({ request: req, principal, requestId, handler: async (sql) => { const body = await contractBody(req, SettingsEndpointContracts.member); const email = body.email.toLowerCase(); const name = body.name ?? null; const memberRole = body.role; enforceRoleCeiling(principal, memberRole); const id = genId("mem"); const rows = await sql<Row[]>`INSERT INTO member (id, workspace_id, email, name, role) VALUES (${id}, ${principal.workspaceId}, ${email}, ${name}, ${memberRole}) ON CONFLICT (workspace_id, email) DO NOTHING RETURNING id, email, name, role, disabled_at, created_at`; const row = rows[0]; if (!row) throw new ManifoldError({ status: 409, code: "VALIDATION", message: "a member with that email already exists", reasonCodes: ["MEMBER_EMAIL_EXISTS"] }); await audit(sql, principal, { action: "member.create", targetKind: "member", targetId: id, requestId, detail: { email, role: memberRole } }); return contractOk(SettingsEndpointContracts.memberResponse, { data: { id: row.id, email: row.email, name: row.name, role: row.role, status: "active", createdAt: row.created_at } }, requestId, 201); } }); }); }
