import { audit } from "@/lib/audit";
import { wrapInEnvelope } from "@/lib/http";
import { contractBody, contractOk, contractQuery } from "@/lib/contracts";
import { SettingsEndpointContracts } from "@manifold/contracts";
import { runMutationGuard } from "@/lib/mutation-guard";
import { authorizeSettings } from "@/lib/settings/access";
import { enforceRoleCeiling, enforceTargetCeiling, notFound } from "@/lib/settings/crud";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
export async function PATCH(req: Request, ctx: { params: Promise<{ id: string }> }) { return wrapInEnvelope(async (requestId) => { contractQuery(new URL(req.url).searchParams, SettingsEndpointContracts.emptyQuery); const principal = await authorizeSettings(req, "config:write"); const { id } = await ctx.params; return runMutationGuard({ request: req, principal, requestId, handler: async (sql) => { const body = await contractBody(req, SettingsEndpointContracts.memberUpdate); const current = (await sql<{ role: string; disabled_at: string | null }[]>`SELECT role, disabled_at FROM member WHERE id = ${id} AND workspace_id = ${principal.workspaceId} LIMIT 1`)[0]; if (!current) throw notFound("member"); enforceTargetCeiling(principal, current.role); if (body.role !== undefined) enforceRoleCeiling(principal, body.role); const nextRole = body.role ?? current.role; const disabled = body.disabled ?? current.disabled_at !== null; const row = (await sql<{ id: string; email: string; name: string | null; role: string; disabled_at: string | null; created_at: string }[]>`UPDATE member SET role = ${nextRole}, disabled_at = ${disabled ? new Date().toISOString() : null}, updated_at = now() WHERE id = ${id} AND workspace_id = ${principal.workspaceId} RETURNING id, email, name, role, disabled_at, created_at`)[0]!; await audit(sql, principal, { action: "member.update", targetKind: "member", targetId: id, requestId, detail: { role: nextRole, disabled } }); return contractOk(SettingsEndpointContracts.memberResponse, { data: { id: row.id, email: row.email, name: row.name, role: row.role, status: row.disabled_at ? "disabled" : "active", createdAt: row.created_at } }, requestId); } }); }); }
