"use client";

import { useCallback, useEffect, useRef, useState, type ReactNode } from "react";
import { useSearchParams } from "next/navigation";
import { EmptyState, PageFrame } from "@/components/console/page-frame";
import { AlertBanner } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, Skeleton } from "@/components/ui/card";
import { Input } from "@/components/ui/field";
import { StatusBadge } from "@/components/ui/status";
import { apiRequest } from "@/lib/api-client";
import { InvitationsPanel, ServiceAccountsPanel, SessionsPanel } from "@/components/settings/human-auth-panels";

type Page<T> = { data: T[]; nextCursor: string | null };
type Workspace = { id: string; slug: string; name: string; region: string; storagePolicy: { ceilingBytes: string; warnPct: number; highPct: number; critPct: number }; updatedAt: string };
type Member = { id: string; email: string; name: string | null; role: string; status: string; createdAt: string };
type Team = { id: string; slug: string; name: string; costCenterId: string | null; createdAt: string };
type CostCenter = { id: string; slug: string; name: string; parentId: string | null; createdAt: string };
type Token = { id: string; displayPrefix: string; kind: "legacy" | "personal" | "serviceAccount"; name: string | null; scopes: unknown; createdByMemberId: string | null; expiresAt: string | null; revokedAt: string | null; lastUsedAt: string | null; createdAt: string };
type App = { id: string; slug: string; name: string; status: string; actions: Array<{ id: string; slug: string; name: string | null; source: string }> };
type Alert = { id: string; scopeType: string; scopeId: string | null; metric: string; threshold: string; window: string; destinations: unknown; status: string };
type CliAuthorization = { id: string; userCode: string; status: string; requestedScopes: unknown; client: { id: string; name: string }; verificationOrigin: string; expiresAt: string; canReview: boolean };
type Danger = { data: { workspaceDeletion: { available: boolean; reasonCode: string; message: string }; dependencies: { members: number; teams: number; costCenters: number; apps: number; activeTokens: number; observations: number } } };
type Tab = "workspace" | "members" | "invitations" | "sessions" | "serviceAccounts" | "teams" | "costCenters" | "tokens" | "cli" | "apps" | "alerts" | "danger";
const tabs: Array<{ id: Tab; label: string }> = [{ id: "workspace", label: "Workspace" }, { id: "members", label: "Members" }, { id: "invitations", label: "Invitations" }, { id: "sessions", label: "Sessions" }, { id: "serviceAccounts", label: "Service accounts" }, { id: "teams", label: "Teams" }, { id: "costCenters", label: "Cost centers" }, { id: "tokens", label: "Tokens" }, { id: "cli", label: "CLI auth" }, { id: "apps", label: "Apps" }, { id: "alerts", label: "Alerts" }, { id: "danger", label: "Danger zone" }];
function when(value: string | null | undefined) { if (!value) return "Never"; const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(date); }
function words(value: unknown) { return Array.isArray(value) && value.length ? value.filter((item): item is string => typeof item === "string").join(", ") : "No explicit scopes"; }
function destinations(value: unknown) { if (Array.isArray(value)) { const labels = value.filter((item): item is string => typeof item === "string"); return labels.length ? labels.join(", ") : `${value.length} configured`; } return value ? "Configured" : "None"; }
function nameFor<T extends { id: string; name: string | null }>(items: T[] | null, id: string | null) { return id ? items?.find((item) => item.id === id)?.name ?? "Unavailable" : "None"; }

export function SettingsConsole() {
  const search = useSearchParams(); const cliAuth = search.get("cli_auth");
  const [tab, setTab] = useState<Tab>(cliAuth ? "cli" : "workspace"); const [workspace, setWorkspace] = useState<Workspace | null>(null); const [members, setMembers] = useState<Member[] | null>(null); const [teams, setTeams] = useState<Team[] | null>(null); const [costCenters, setCostCenters] = useState<CostCenter[] | null>(null); const [tokens, setTokens] = useState<Token[] | null>(null); const [apps, setApps] = useState<App[] | null>(null); const [alerts, setAlerts] = useState<Alert[] | null>(null); const [cli, setCli] = useState<CliAuthorization[] | null>(null); const [danger, setDanger] = useState<Danger["data"] | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { if (cliAuth) setTab("cli"); }, [cliAuth]);
  const load = useCallback(async () => { setError(null); try { const [workspaceResult, memberResult, teamResult, centerResult, tokenResult, appResult, alertResult, cliResult, dangerResult] = await Promise.all([apiRequest<{ data: Workspace }>("/settings/workspace"), apiRequest<Page<Member>>("/settings/members"), apiRequest<Page<Team>>("/settings/teams"), apiRequest<Page<CostCenter>>("/settings/cost-centers"), apiRequest<Page<Token>>("/settings/tokens"), apiRequest<Page<App>>("/settings/apps"), apiRequest<Page<Alert>>("/settings/alerts"), apiRequest<Page<CliAuthorization>>("/settings/cli-auth"), apiRequest<Danger>("/settings/danger-zone")]); setWorkspace(workspaceResult.data); setMembers(memberResult.data); setTeams(teamResult.data); setCostCenters(centerResult.data); setTokens(tokenResult.data); setApps(appResult.data); setAlerts(alertResult.data); setCli(cliResult.data); setDanger(dangerResult.data); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load settings"); } }, []);
  useEffect(() => { void load(); }, [load]);
  const saveWorkspace = async (name: string) => { if (!workspace || saving) return; setSaving(true); try { const result = await apiRequest<{ data: Workspace }>("/settings/workspace", { method: "PATCH", body: { name } }); setWorkspace(result.data); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update workspace"); } finally { setSaving(false); } };
  const mutate = async (path: string, method: string, body?: unknown) => { if (saving) return null; setSaving(true); setError(null); try { const result = await apiRequest<{ data: unknown }>(path, { method, body }); await load(); return result.data; } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save settings"); return null; } finally { setSaving(false); } };
  const loading = workspace === null && !error;
  return <PageFrame description="Manage workspace administration and supported controls" title="Settings">{error ? <AlertBanner title="Settings unavailable" tone="down">{error} <Button onClick={() => void load()} variant="ghost">Retry load</Button></AlertBanner> : null}<nav aria-label="Settings sections" style={{ display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 16 }}>{tabs.map((item) => <Button aria-pressed={tab === item.id} key={item.id} onClick={() => setTab(item.id)} variant={tab === item.id ? "primary" : "outline"}>{item.label}</Button>)}</nav>{loading ? <Loading /> : null}{tab === "workspace" && workspace ? <WorkspacePanel onSave={saveWorkspace} saving={saving} workspace={workspace} /> : null}{tab === "members" ? <MembersPanel members={members} mutate={mutate} onOpenInvitations={() => setTab("invitations")} saving={saving} /> : null}{tab === "invitations" ? <InvitationsPanel /> : null}{tab === "sessions" ? <SessionsPanel /> : null}{tab === "serviceAccounts" ? <ServiceAccountsPanel /> : null}{tab === "teams" ? <TeamsPanel costCenters={costCenters} mutate={mutate} saving={saving} teams={teams} /> : null}{tab === "costCenters" ? <CentersPanel centers={costCenters} mutate={mutate} saving={saving} /> : null}{tab === "tokens" ? <TokensPanel members={members} mutate={mutate} saving={saving} tokens={tokens} /> : null}{tab === "cli" ? <CliPanel focusCode={cliAuth} items={cli} /> : null}{tab === "apps" ? <AppsPanel apps={apps} mutate={mutate} saving={saving} /> : null}{tab === "alerts" ? <AlertsPanel alerts={alerts} /> : null}{tab === "danger" ? <DangerPanel danger={danger} /> : null}</PageFrame>;
}

function Loading() { return <Card className="console-card-body"><Skeleton style={{ height: 32 }} /><Skeleton style={{ height: 80, marginTop: 12 }} /><Skeleton style={{ height: 80, marginTop: 12 }} /></Card>; }
function WorkspacePanel({ workspace, onSave, saving }: { workspace: Workspace; onSave: (name: string) => void; saving: boolean }) { const [name, setName] = useState(workspace.name); useEffect(() => setName(workspace.name), [workspace.name]); return <Card className="console-card-body"><h2 style={{ marginTop: 0 }}>Workspace details</h2><form className="console-form" onSubmit={(event) => { event.preventDefault(); onSave(name); }}><label className="console-field"><span>Workspace name</span><Input disabled={saving} onChange={(event) => setName(event.target.value)} required value={name} /></label><dl style={{ display: "grid", gap: 10, margin: 0 }}><div><dt className="console-faint">Slug</dt><dd>{workspace.slug}</dd></div><div><dt className="console-faint">Region</dt><dd>{workspace.region}</dd></div><div><dt className="console-faint">Storage policy</dt><dd>{workspace.storagePolicy.ceilingBytes} bytes with {workspace.storagePolicy.warnPct}% warning, {workspace.storagePolicy.highPct}% high, and {workspace.storagePolicy.critPct}% critical thresholds</dd></div></dl><Button disabled={saving || name.trim() === workspace.name} type="submit" variant="primary">{saving ? "Saving workspace" : "Save workspace name"}</Button></form></Card>; }
type Mutate = (path: string, method: string, body?: unknown) => Promise<unknown>;
function MembersPanel({ members, mutate, saving, onOpenInvitations }: { members: Member[] | null; mutate: Mutate; saving: boolean; onOpenInvitations: () => void }) { if (!members) return <Loading />; return <><AlertBanner title="Invite people to join" tone="verifying">New members create their own password from an invitation. <Button onClick={onOpenInvitations} variant="ghost">Open invitations</Button></AlertBanner><Table headings={["Member", "Role", "Status", "Joined", ""]}>{members.map((member) => <tr key={member.id}><td>{member.name ?? member.email}<div className="console-faint">{member.email}</div></td><td>{member.role}</td><td><StatusBadge status={member.status === "active" ? "up" : "down"}>{member.status}</StatusBadge></td><td>{when(member.createdAt)}</td><td>{member.status === "active" ? <Button disabled={saving} onClick={() => { if (window.confirm(`Disable ${member.email}?`)) void mutate(`/settings/members/${member.id}`, "PATCH", { disabled: true }); }} variant="outline">Disable</Button> : null}</td></tr>)}</Table></>; }
function TeamsPanel({ teams, costCenters, mutate, saving }: { teams: Team[] | null; costCenters: CostCenter[] | null; mutate: Mutate; saving: boolean }) { const [name, setName] = useState(""); const [slugValue, setSlug] = useState(""); if (!teams) return <Loading />; return <><CreateForm title="Create team" saving={saving} onSubmit={() => void mutate("/settings/teams", "POST", { name, slug: slugValue, costCenterId: null }).then(() => { setName(""); setSlug(""); })}><Input onChange={(e) => setName(e.target.value)} placeholder="Team name" required value={name} /><Input onChange={(e) => setSlug(e.target.value)} placeholder="team-slug" required value={slugValue} /></CreateForm><Table headings={["Team", "Cost center", "Created", ""]}>{teams.map((team) => <tr key={team.id}><td>{team.name}<div className="console-faint">{team.slug}</div></td><td>{nameFor(costCenters, team.costCenterId)}</td><td>{when(team.createdAt)}</td><td><ArchiveButton disabled={saving} label={team.name} onArchive={() => mutate(`/settings/teams/${team.id}`, "DELETE")} /></td></tr>)}</Table></>; }
function CentersPanel({ centers, mutate, saving }: { centers: CostCenter[] | null; mutate: Mutate; saving: boolean }) { const [name, setName] = useState(""); const [slugValue, setSlug] = useState(""); if (!centers) return <Loading />; return <><CreateForm title="Create cost center" saving={saving} onSubmit={() => void mutate("/settings/cost-centers", "POST", { name, slug: slugValue, parentId: null }).then(() => { setName(""); setSlug(""); })}><Input onChange={(e) => setName(e.target.value)} placeholder="Cost center name" required value={name} /><Input onChange={(e) => setSlug(e.target.value)} placeholder="cost-center-slug" required value={slugValue} /></CreateForm><Table headings={["Cost center", "Parent", "Created", ""]}>{centers.map((center) => <tr key={center.id}><td>{center.name}<div className="console-faint">{center.slug}</div></td><td>{nameFor(centers, center.parentId)}</td><td>{when(center.createdAt)}</td><td><ArchiveButton disabled={saving} label={center.name} onArchive={() => mutate(`/settings/cost-centers/${center.id}`, "DELETE")} /></td></tr>)}</Table></>; }
function TokensPanel({ tokens, members, mutate, saving }: { tokens: Token[] | null; members: Member[] | null; mutate: Mutate; saving: boolean }) { const [name, setName] = useState(""); const [scopes, setScopes] = useState("config:read"); const [secret, setSecret] = useState<string | null>(null); if (!tokens) return <Loading />; return <><CreateForm title="Create personal API token" saving={saving} onSubmit={() => void mutate("/settings/tokens", "POST", { kind: "personal", name, scopes: scopes.split(",").map((s) => s.trim()).filter(Boolean) }).then((result) => { const item = result as { plaintext?: string } | null; if (item?.plaintext) { setSecret(item.plaintext); setName(""); } })}><Input aria-label="Token name" onChange={(e) => setName(e.target.value)} placeholder="Local development" required value={name} /><Input aria-label="Token scopes" onChange={(e) => setScopes(e.target.value)} placeholder="scope, scope" required value={scopes} /></CreateForm>{secret ? <AlertBanner title="Copy this token now" tone="verifying"><code className="console-code">{secret}</code><Button onClick={() => { void navigator.clipboard.writeText(secret); }} variant="outline">Copy</Button><Button onClick={() => setSecret(null)} variant="outline">I stored it</Button></AlertBanner> : null}<Table headings={["Token", "Scopes", "Issued by", "Use and expiry", "Status", ""]}>{tokens.map((token) => <tr key={token.id}><td>{token.name ?? "Unlabeled legacy token"}<div className="console-faint console-mono">{token.displayPrefix} · {token.kind}</div></td><td>{words(token.scopes)}</td><td>{nameFor(members, token.createdByMemberId)}</td><td>Last used {when(token.lastUsedAt)}<div className="console-faint">Expires {when(token.expiresAt)}</div></td><td><StatusBadge status={token.revokedAt ? "down" : "up"}>{token.revokedAt ? "Revoked" : "Active"}</StatusBadge></td><td>{!token.revokedAt ? <Button disabled={saving} onClick={() => { if (window.confirm(`Revoke ${token.displayPrefix}?`)) void mutate(`/settings/tokens/${token.id}/revoke`, "POST", {}); }} variant="danger">Revoke</Button> : null}</td></tr>)}</Table></>; }
function CliPanel({ items, focusCode }: { items: CliAuthorization[] | null; focusCode: string | null }) {
  const [working, setWorking] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [local, setLocal] = useState(items); const focused = useRef<HTMLTableRowElement | null>(null);
  useEffect(() => setLocal(items), [items]); useEffect(() => { const match = local?.find((item) => item.userCode === focusCode && item.status === "pending"); if (match && focused.current) { focused.current.scrollIntoView({ block: "center" }); focused.current.focus(); } }, [focusCode, local]); if (!local) return <Loading />;
  const review = async (item: CliAuthorization, decision: "approve" | "deny") => { setWorking(`${item.id}:${decision}`); setError(null); try { const result = await apiRequest<{ data: { status: string } }>(`/settings/cli-auth/${decision}`, { method: "POST", body: { userCode: item.userCode } }); setLocal((current) => current?.map((entry) => entry.id === item.id ? { ...entry, status: result.data.status, canReview: false } : entry) ?? null); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to review authorization"); } finally { setWorking(null); } };
  return <>{error ? <AlertBanner title="CLI authorization review failed" tone="down">{error}</AlertBanner> : null}<AlertBanner title="Review every binding before approving" tone="verifying">Approval mints a token only after the device exchanges its private code. Verify the code, the server-derived console origin, client, and every requested scope with the person at the terminal.</AlertBanner>{local.length ? <Table headings={["User code", "Requested scopes", "Trusted binding", "State", "Expires", "Review"]}>{local.map((item) => <tr key={item.id} ref={item.userCode === focusCode && item.status === "pending" ? focused : undefined} tabIndex={item.userCode === focusCode && item.status === "pending" ? -1 : undefined}><td className="console-mono">{item.userCode}</td><td>{words(item.requestedScopes)}</td><td>{item.client.name}<div className="console-faint">{item.client.id} · {item.verificationOrigin}</div></td><td><StatusBadge status={item.status === "pending" ? "idle" : item.status === "issued" || item.status === "approved" ? "up" : "down"}>{item.status}</StatusBadge></td><td>{when(item.expiresAt)}</td><td>{item.canReview ? <div style={{ display: "flex", gap: 8 }}><Button disabled={working !== null} onClick={() => void review(item, "approve")} variant="primary">{working === `${item.id}:approve` ? "Approving" : "Approve"}</Button><Button disabled={working !== null} onClick={() => void review(item, "deny")} variant="outline">{working === `${item.id}:deny` ? "Denying" : "Deny"}</Button></div> : "No action"}</td></tr>)}</Table> : <Empty title="No CLI authorization requests" description="Pending requests will appear here for explicit human review" />}</>;
}
function AppsPanel({ apps, mutate, saving }: { apps: App[] | null; mutate: Mutate; saving: boolean }) { const [name, setName] = useState(""); const [slugValue, setSlug] = useState(""); if (!apps) return <Loading />; return <><CreateForm title="Create app" saving={saving} onSubmit={() => void mutate("/settings/apps", "POST", { name, slug: slugValue, defaultCapturePolicy: {} }).then(() => { setName(""); setSlug(""); })}><Input onChange={(e) => setName(e.target.value)} placeholder="App name" required value={name} /><Input onChange={(e) => setSlug(e.target.value)} placeholder="app-slug" required value={slugValue} /></CreateForm><Table headings={["App", "Actions", "Status", ""]}>{apps.map((app) => <tr key={app.id}><td>{app.name}<div className="console-faint">{app.slug}</div></td><td>{app.actions.length ? app.actions.map((action) => <div key={action.id}>{action.name ?? action.slug} <span className="console-faint">{action.source}</span></div>) : "No actions"}</td><td><StatusBadge status={app.status === "active" ? "up" : "idle"}>{app.status}</StatusBadge></td><td><ArchiveButton disabled={saving} label={app.name} onArchive={() => mutate(`/settings/apps/${app.id}`, "DELETE")} /></td></tr>)}</Table></>; }
function AlertsPanel({ alerts }: { alerts: Alert[] | null }) { if (!alerts) return <Loading />; if (!alerts.length) return <Empty title="No alert rules" description="Alert destination changes are not available from this API" />; return <Table headings={["Metric", "Scope", "Threshold", "Window", "Destinations", "Status"]}>{alerts.map((alert) => <tr key={alert.id}><td>{alert.metric}</td><td>{alert.scopeType}</td><td>{alert.threshold}</td><td>{alert.window}</td><td>{destinations(alert.destinations)}</td><td><StatusBadge status={alert.status === "active" ? "up" : "idle"}>{alert.status}</StatusBadge></td></tr>)}</Table>; }
function DangerPanel({ danger }: { danger: Danger["data"] | null }) { if (!danger) return <Loading />; const dependency = danger.dependencies; return <><AlertBanner title="Workspace deletion unavailable" tone="down">{danger.workspaceDeletion.message}</AlertBanner><Card className="console-card-body"><h2 style={{ marginTop: 0 }}>Dependency readiness</h2><p className="console-muted">Deletion has no supported request. The following records would require a separate, deliberate migration plan</p><dl style={{ display: "grid", gap: 8, margin: 0 }}><div>Members: {dependency.members}</div><div>Teams: {dependency.teams}</div><div>Cost centers: {dependency.costCenters}</div><div>Apps: {dependency.apps}</div><div>Active API tokens: {dependency.activeTokens}</div><div>Observations: {dependency.observations}</div></dl></Card></>; }
function Empty({ title, description }: { title: string; description: string }) { return <Card><EmptyState description={description} title={title} /></Card>; }
function CreateForm({ title, children, onSubmit, saving }: { title: string; children: ReactNode; onSubmit: () => void; saving: boolean }) { return <Card className="console-card-body" style={{ marginBottom: 16 }}><form className="console-form" onSubmit={(event) => { event.preventDefault(); onSubmit(); }}><strong>{title}</strong><div className="console-form-row">{children}</div><div><Button disabled={saving} type="submit" variant="primary">{saving ? "Saving" : title}</Button></div></form></Card>; }
function ArchiveButton({ label, onArchive, disabled }: { label: string; onArchive: () => Promise<unknown>; disabled: boolean }) { return <Button disabled={disabled} onClick={() => { if (window.confirm(`Archive ${label}? This keeps historical data but removes it from active configuration.`)) void onArchive(); }} variant="danger">Archive</Button>; }
function Table({ headings, children }: { headings: string[]; children: ReactNode }) { return <div className="console-table-wrap"><table className="console-table"><thead><tr>{headings.map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
