"use client";

import { useEffect, useRef, useState } from "react";
import { Button } from "./button";

function useOverlay(open: boolean, onClose: () => void, initialFocus?: React.RefObject<HTMLElement | null>) {
  const previousFocus = useRef<HTMLElement | null>(null);
  useEffect(() => { if (!open) return; previousFocus.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; const key = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); if (event.key === "Tab") { const dialog = document.querySelector<HTMLElement>('[role="dialog"]'); const focusable = dialog ? Array.from(dialog.querySelectorAll<HTMLElement>('button, input, select, textarea, a[href]')).filter((element) => !element.hasAttribute("disabled")) : []; const current = focusable.indexOf(document.activeElement as HTMLElement); if (!focusable.length) return; if (event.shiftKey && current <= 0) { event.preventDefault(); focusable.at(-1)?.focus(); } else if (!event.shiftKey && current === focusable.length - 1) { event.preventDefault(); focusable[0]?.focus(); } } }; document.addEventListener("keydown", key); initialFocus?.current?.focus(); return () => { document.removeEventListener("keydown", key); previousFocus.current?.focus(); }; }, [open, onClose, initialFocus]);
}
export function Sheet({ open, onClose, title, children }: { open: boolean; onClose: () => void; title: string; children: React.ReactNode }) { const closeRef = useRef<HTMLButtonElement>(null); useOverlay(open, onClose, closeRef); if (!open) return null; return <div className="cp-dialog-backdrop" onMouseDown={onClose} role="presentation"><aside aria-label={title} aria-modal="true" className="cp-sheet" onMouseDown={(event) => event.stopPropagation()} role="dialog"><header style={{ alignItems: "center", display: "flex", justifyContent: "space-between", marginBottom: 18 }}><h2 style={{ fontSize: 16, margin: 0 }}>{title}</h2><Button aria-label="Close panel" onClick={onClose} ref={closeRef}>Close</Button></header>{children}</aside></div>; }
export function ConfirmDialog({ open, onClose, onConfirm, title, description, confirmLabel = "Confirm", confirmText }: { open: boolean; onClose: () => void; onConfirm: () => void; title: string; description: string; confirmLabel?: string; confirmText?: string }) { const cancelRef = useRef<HTMLButtonElement>(null); const [typed, setTyped] = useState(""); useOverlay(open, onClose, cancelRef); useEffect(() => { if (!open) setTyped(""); }, [open]); if (!open) return null; return <div className="cp-dialog-backdrop" onMouseDown={onClose} role="presentation"><div aria-describedby="dialog-description" aria-labelledby="dialog-title" aria-modal="true" className="cp-dialog" onMouseDown={(event) => event.stopPropagation()} role="dialog"><h2 id="dialog-title" style={{ fontSize: 16, margin: "0 0 8px" }}>{title}</h2><p id="dialog-description" style={{ color: "var(--fg-muted)", margin: "0 0 16px" }}>{description}</p>{confirmText ? <label style={{ display: "grid", fontSize: 12, gap: 6, marginBottom: 16 }}>Type <span className="cp-mono">{confirmText}</span> to confirm<input className="cp-input" onChange={(event) => setTyped(event.target.value)} value={typed} /></label> : null}<footer style={{ display: "flex", gap: 8, justifyContent: "flex-end" }}><Button onClick={onClose} ref={cancelRef}>Cancel</Button><Button disabled={Boolean(confirmText && typed !== confirmText)} onClick={onConfirm} variant="danger">{confirmLabel}</Button></footer></div></div>; }
