import { audit } from "@/lib/audit";
import { ManifoldError, wrapInEnvelope } from "@/lib/http";
import { contractBody, contractOk, contractOptionalEmptyBody, contractQuery } from "@/lib/contracts";
import { EmptyRequest, SettingsEndpointContracts } from "@manifold/contracts";
import { runMutationGuard } from "@/lib/mutation-guard";
import { authorizeSettings } from "@/lib/settings/access";
import { notFound } from "@/lib/settings/crud";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
type App = { id: string; slug: string; name: string; status: string; default_capture_policy: unknown; created_at: string };
export async function PATCH(req: Request, ctx: { params: Promise<{ id: string }> }) { return mutate(req, ctx, false); }
export async function DELETE(req: Request, ctx: { params: Promise<{ id: string }> }) { return mutate(req, ctx, true); }
async function mutate(req: Request, ctx: { params: Promise<{ id: string }> }, archive: boolean): Promise<Response> { return wrapInEnvelope(async (requestId) => { contractQuery(new URL(req.url).searchParams, SettingsEndpointContracts.emptyQuery); const principal = await authorizeSettings(req, "config:write"); const { id } = await ctx.params; return runMutationGuard({ request: req, principal, requestId, handler: async (sql) => { const value = archive ? (await contractOptionalEmptyBody(req.clone(), EmptyRequest), {}) : await contractBody(req.clone(), SettingsEndpointContracts.appUpdate); const current = (await sql<App[]>`SELECT id, slug, name, status, default_capture_policy, created_at FROM app WHERE id = ${id} AND workspace_id = ${principal.workspaceId} AND archived_at IS NULL`)[0]; if (!current) throw notFound("app"); if (archive) { const keys = (await sql<{ id: string }[]>`SELECT id FROM virtual_key WHERE workspace_id = ${principal.workspaceId} AND (default_app_id = ${id} OR allowed_app_ids @> ${sql.json([id] as never)}) AND revoked_at IS NULL LIMIT 1`)[0]; if (keys) throw new ManifoldError({ status: 409, code: "VALIDATION", message: "revoke or update active keys before archiving this app", reasonCodes: ["APP_IN_USE"] }); await sql`UPDATE app SET status = 'archived', archived_at = now(), updated_at = now() WHERE id = ${id} AND workspace_id = ${principal.workspaceId}`; await sql`UPDATE action SET archived_at = now(), updated_at = now() WHERE app_id = ${id} AND workspace_id = ${principal.workspaceId} AND archived_at IS NULL`; await audit(sql, principal, { action: "app.archive", targetKind: "app", targetId: id, requestId }); return contractOk(SettingsEndpointContracts.appArchived, { data: { id, archived: true } }, requestId); } const policy = value.defaultCapturePolicy ?? current.default_capture_policy; const row = (await sql<App[]>`UPDATE app SET slug = ${value.slug ?? current.slug}, name = ${value.name ?? current.name}, default_capture_policy = ${sql.json(policy as never)}, updated_at = now() WHERE id = ${id} AND workspace_id = ${principal.workspaceId} RETURNING id, slug, name, status, default_capture_policy, created_at`)[0]!; await audit(sql, principal, { action: "app.update", targetKind: "app", targetId: id, requestId, detail: { slug: value.slug ?? current.slug, name: value.name ?? current.name } }); return contractOk(SettingsEndpointContracts.appResponse, { data: { id: row.id, slug: row.slug, name: row.name, status: row.status, defaultCapturePolicy: row.default_capture_policy, createdAt: row.created_at } }, requestId); } }); }); }
