import { audit } from "@/lib/audit";
import { ManifoldError, wrapInEnvelope } from "@/lib/http";
import { contractBody, contractOk, contractOptionalEmptyBody, contractQuery } from "@/lib/contracts";
import { EmptyRequest, SettingsEndpointContracts } from "@manifold/contracts";
import { runMutationGuard } from "@/lib/mutation-guard";
import { authorizeSettings } from "@/lib/settings/access";
import { notFound } from "@/lib/settings/crud";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
export async function PATCH(req: Request, ctx: { params: Promise<{ id: string; actionId: string }> }) { return mutate(req, ctx, false); }
export async function DELETE(req: Request, ctx: { params: Promise<{ id: string; actionId: string }> }) { return mutate(req, ctx, true); }
async function mutate(req: Request, ctx: { params: Promise<{ id: string; actionId: string }> }, archive: boolean): Promise<Response> { return wrapInEnvelope(async (requestId) => { contractQuery(new URL(req.url).searchParams, SettingsEndpointContracts.emptyQuery); const principal = await authorizeSettings(req, "config:write"); const { id: appId, actionId } = await ctx.params; return runMutationGuard({ request: req, principal, requestId, handler: async (sql) => { const value = archive ? (await contractOptionalEmptyBody(req.clone(), EmptyRequest), {}) : await contractBody(req.clone(), SettingsEndpointContracts.actionUpdate); const current = (await sql<{ id: string; slug: string; name: string | null; source: string }[]>`SELECT id, slug, name, source FROM action WHERE id = ${actionId} AND app_id = ${appId} AND workspace_id = ${principal.workspaceId} AND archived_at IS NULL`)[0]; if (!current) throw notFound("action"); if (archive) { const key = (await sql<{ id: string }[]>`SELECT id FROM virtual_key WHERE default_action_id = ${actionId} AND workspace_id = ${principal.workspaceId} AND revoked_at IS NULL LIMIT 1`)[0]; if (key) throw new ManifoldError({ status: 409, code: "VALIDATION", message: "revoke or update active keys before archiving this action", reasonCodes: ["ACTION_IN_USE"] }); await sql`UPDATE action SET archived_at = now(), updated_at = now() WHERE id = ${actionId} AND workspace_id = ${principal.workspaceId}`; await audit(sql, principal, { action: "action.archive", targetKind: "action", targetId: actionId, requestId }); return contractOk(SettingsEndpointContracts.actionArchived, { data: { id: actionId, archived: true } }, requestId); } const row = (await sql<{ id: string; slug: string; name: string | null; source: string }[]>`UPDATE action SET slug = ${value.slug ?? current.slug}, name = ${value.name === undefined ? current.name : value.name}, updated_at = now() WHERE id = ${actionId} AND workspace_id = ${principal.workspaceId} RETURNING id, slug, name, source`)[0]!; await audit(sql, principal, { action: "action.update", targetKind: "action", targetId: actionId, requestId, detail: { slug: value.slug ?? current.slug, name: value.name === undefined ? current.name : value.name } }); return contractOk(SettingsEndpointContracts.actionResponse, { data: row }, requestId); } }); }); }
