import { withWorkspace } from "@/lib/db";
import { ManifoldError, wrapInEnvelope } from "@/lib/http";
import { authorizeSettings } from "@/lib/settings/access";
import { audit } from "@/lib/audit";
import { generateSecret } from "@/lib/crypto";
import { genId } from "@/lib/ids";
import { runMutationGuard } from "@/lib/mutation-guard";
import { exactFields, invalid } from "@/lib/settings/crud";
import { contractBody, contractOk, contractQuery } from "@/lib/contracts";
import { SettingsEndpointContracts } from "@manifold/contracts";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
type Row = { id: string; display_prefix: string; scopes: unknown; created_by: string | null; expires_at: string | null; revoked_at: string | null; last_used_at: string | null; created_at: string };
export async function GET(req: Request) { return wrapInEnvelope(async (requestId) => { const { cursor, limit } = contractQuery(new URL(req.url).searchParams, SettingsEndpointContracts.pageQuery); const principal = await authorizeSettings(req, "config:read"); const rows = await withWorkspace(principal.workspaceId, (sql) => sql<Row[]>`SELECT id, display_prefix, scopes, created_by, expires_at, revoked_at, last_used_at, created_at FROM api_token WHERE workspace_id = ${principal.workspaceId} AND (${cursor}::text IS NULL OR id < ${cursor}) ORDER BY id DESC LIMIT ${limit + 1}`); const data = rows.slice(0, limit).map((row) => ({ id: row.id, displayPrefix: row.display_prefix, scopes: Array.isArray(row.scopes) ? row.scopes : [], createdByMemberId: row.created_by, expiresAt: row.expires_at, revokedAt: row.revoked_at, lastUsedAt: row.last_used_at, createdAt: row.created_at })); return contractOk(SettingsEndpointContracts.tokenList, { data, nextCursor: rows.length > limit ? data.at(-1)?.id ?? null : null }, requestId); }); }
export async function POST(req: Request) { return wrapInEnvelope(async (requestId) => { contractQuery(new URL(req.url).searchParams, SettingsEndpointContracts.emptyQuery); const principal = await authorizeSettings(req, "config:write"); return runMutationGuard({ request: req, principal, requestId, rateLimit: { limit: 10, windowMs: 60_000 }, handler: async (sql) => { const body = await contractBody(req, SettingsEndpointContracts.tokenMint); exactFields(body, ["scopes", "expiresAt"], "token minting"); if (!Array.isArray(body.scopes) || !body.scopes.length || body.scopes.some((scope) => typeof scope !== "string" || !scope.trim())) throw invalid("scopes", "scopes must be a non-empty array of strings"); const scopes = [...new Set((body.scopes as string[]).map((scope) => scope.trim()))]; const expiresAt = body.expiresAt === undefined || body.expiresAt === null ? null : typeof body.expiresAt === "string" && Date.parse(body.expiresAt) > Date.now() ? new Date(body.expiresAt).toISOString() : (() => { throw invalid("expiresAt", "expiresAt must be a future ISO timestamp or null"); })(); const secret = generateSecret("mf_tok_"); const id = genId("tok"); await sql`INSERT INTO api_token (id, workspace_id, display_prefix, keyed_hash, scopes, created_by, expires_at) VALUES (${id}, ${principal.workspaceId}, ${secret.displayPrefix}, ${secret.keyedHash}, ${sql.json(scopes as never)}, ${principal.member!.id}, ${expiresAt})`; await audit(sql, principal, { action: "api_token.mint", targetKind: "api_token", targetId: id, requestId, detail: { scopes, expiresAt } }); return contractOk(SettingsEndpointContracts.tokenMintResponse, { data: { id, displayPrefix: secret.displayPrefix, scopes, expiresAt, plaintext: secret.plaintext } }, requestId, 201); } }); }); }
